INSERT INTO category(id,name,lang) VALUES(1,"Passereaux",'fr');
INSERT INTO category(id,name,lang) VALUES(2,"Rapaces",'fr');
INSERT INTO category(id,name,lang) VALUES(3,"Grands échassiers",'fr');
INSERT INTO category(id,name,lang) VALUES(4,"Cygnes, oies, canards",'fr');
INSERT INTO category(id,name,lang) VALUES(5,"Limicoles",'fr');
INSERT INTO category(id,name,lang) VALUES(6,"Gallinacés",'fr');
INSERT INTO category(id,name,lang) VALUES(7,"Corvidés",'fr');
INSERT INTO category(id,name,lang) VALUES(8,"Chouettes, hiboux",'fr');
INSERT INTO category(id,name,lang) VALUES(9,"Fous, cormorans, pélicans",'fr');
INSERT INTO category(id,name,lang) VALUES(10,"Autres",'fr');
INSERT INTO category(id,name,lang) VALUES(11,"Râles, marouettes, poules d'eau",'fr');
INSERT INTO category(id,name,lang) VALUES(12,"Mouettes, goéland, fulmars",'fr');
INSERT INTO category(id,name,lang) VALUES(13,"Labbes",'fr');
INSERT INTO category(id,name,lang) VALUES(14,"Grèbes",'fr');
INSERT INTO category(id,name,lang) VALUES(15,"Sternes",'fr');
INSERT INTO category(id,name,lang) VALUES(16,"Pingouins, guillemots, macareux",'fr');
INSERT INTO category(id,name,lang) VALUES(17,"Martinets et hirondelles",'fr');
INSERT INTO category(id,name,lang) VALUES(18,"Pics",'fr');
INSERT INTO category(id,name,lang) VALUES(19,"Pigeons et tourterelles",'fr');
INSERT INTO category(id,name,lang) VALUES(20,"Plongeons",'fr');
