INSERT INTO category(id,name,lang) VALUES(1,"Passereaux",'fr');
INSERT INTO category(id,name,lang) VALUES(2,"Rapaces",'fr');
INSERT INTO category(id,name,lang) VALUES(3,"Grands échassiers",'fr');
INSERT INTO category(id,name,lang) VALUES(4,"Cygnes, oies, canards",'fr');
INSERT INTO category(id,name,lang) VALUES(5,"Limicoles",'fr');
INSERT INTO category(id,name,lang) VALUES(6,"Gallinacés",'fr');
INSERT INTO category(id,name,lang) VALUES(7,"Corvidés",'fr');
INSERT INTO category(id,name,lang) VALUES(8,"Chouettes, hiboux",'fr');
INSERT INTO category(id,name,lang) VALUES(9,"Fous, cormorans, pélicans",'fr');
INSERT INTO category(id,name,lang) VALUES(10,"Autres",'fr');
INSERT INTO category(id,name,lang) VALUES(11,"Râles, marouettes, poules d'eau",'fr');
INSERT INTO category(id,name,lang) VALUES(12,"Mouettes, goéland, fulmars",'fr');
INSERT INTO category(id,name,lang) VALUES(13,"Labbes",'fr');
INSERT INTO category(id,name,lang) VALUES(14,"Grèbes",'fr');
INSERT INTO category(id,name,lang) VALUES(15,"Sternes",'fr');
INSERT INTO category(id,name,lang) VALUES(16,"Pingouins, guillemots, macareux",'fr');
INSERT INTO category(id,name,lang) VALUES(17,"Martinets et hirondelles",'fr');
INSERT INTO category(id,name,lang) VALUES(18,"Pics",'fr');
INSERT INTO category(id,name,lang) VALUES(19,"Pigeons et tourterelles",'fr');
INSERT INTO category(id,name,lang) VALUES(20,"Plongeons",'fr');

INSERT INTO category(id,name,lang) VALUES(1,"Passerines",'en');
INSERT INTO category(id,name,lang) VALUES(2,"Birds of prey",'en');
INSERT INTO category(id,name,lang) VALUES(3,"Long-legged wading birds",'en');
INSERT INTO category(id,name,lang) VALUES(4,"Swans, gooses, ducks",'en');
INSERT INTO category(id,name,lang) VALUES(5,"Waders",'en');
INSERT INTO category(id,name,lang) VALUES(6,"Galliformes",'en');
INSERT INTO category(id,name,lang) VALUES(7,"Corvidae",'en');
INSERT INTO category(id,name,lang) VALUES(8,"Owls",'en');
INSERT INTO category(id,name,lang) VALUES(9,"Gannets, cormorants, pelicans",'en');
INSERT INTO category(id,name,lang) VALUES(10,"Other",'en');
INSERT INTO category(id,name,lang) VALUES(11,"Crakes, moorhens",'en');
INSERT INTO category(id,name,lang) VALUES(12,"Gulls, fulmars",'en');
INSERT INTO category(id,name,lang) VALUES(13,"Skuas",'en');
INSERT INTO category(id,name,lang) VALUES(14,"Grebes",'en');
INSERT INTO category(id,name,lang) VALUES(15,"Terns",'en');
INSERT INTO category(id,name,lang) VALUES(16,"Penguins, guillemots, puffins",'en');
INSERT INTO category(id,name,lang) VALUES(17,"Swifts and swallows",'en');
INSERT INTO category(id,name,lang) VALUES(18,"Woodpeckers",'en');
INSERT INTO category(id,name,lang) VALUES(19,"Pigeons and doves",'en');
INSERT INTO category(id,name,lang) VALUES(20,"Divers",'en');

INSERT INTO category(id,name,lang) VALUES(1,"Sperlingsvögel",'de');
INSERT INTO category(id,name,lang) VALUES(2,"Raubvögel",'de');
INSERT INTO category(id,name,lang) VALUES(3,"Grosse Stelzvögel",'de');
INSERT INTO category(id,name,lang) VALUES(4,"Schwäne, Gänse, Enten",'de');
INSERT INTO category(id,name,lang) VALUES(5,"Schnepfenvögel",'de');
INSERT INTO category(id,name,lang) VALUES(6,"Hühnervögel",'de');
INSERT INTO category(id,name,lang) VALUES(7,"Rabenvögel",'de');
INSERT INTO category(id,name,lang) VALUES(8,"Eulen",'de');
INSERT INTO category(id,name,lang) VALUES(9,"Tölpel, Kormorane, Pelikane",'de');
INSERT INTO category(id,name,lang) VALUES(10,"Andere Vögel",'de');
INSERT INTO category(id,name,lang) VALUES(11,"Rallenvögel",'de');
INSERT INTO category(id,name,lang) VALUES(12,"Möwen",'de');
INSERT INTO category(id,name,lang) VALUES(13,"Raubmöwen",'de');
INSERT INTO category(id,name,lang) VALUES(14,"Lappentaucher",'de');
INSERT INTO category(id,name,lang) VALUES(15,"Seeschwalben",'de');
INSERT INTO category(id,name,lang) VALUES(16,"Alkenvögel",'de');
INSERT INTO category(id,name,lang) VALUES(17,"Segler und Schwalben",'de');
INSERT INTO category(id,name,lang) VALUES(18,"Spechte",'de');
INSERT INTO category(id,name,lang) VALUES(19,"Tauben",'de');
INSERT INTO category(id,name,lang) VALUES(20,"Seetaucher",'de');
