INSERT INTO category(id,name,lang) VALUES(1,"Autres",'fr');
INSERT INTO category(id,name,lang) VALUES(2,"Chouettes, hiboux",'fr');
INSERT INTO category(id,name,lang) VALUES(3,"corvidés",'fr');
INSERT INTO category(id,name,lang) VALUES(4,"Cygnes, oies, canards",'fr');
INSERT INTO category(id,name,lang) VALUES(5,"Fous, cormorans, pélicans",'fr');
INSERT INTO category(id,name,lang) VALUES(6,"Gallinacés",'fr');
INSERT INTO category(id,name,lang) VALUES(7,"Grands échassiers",'fr');
INSERT INTO category(id,name,lang) VALUES(8,"Grèbes",'fr');
INSERT INTO category(id,name,lang) VALUES(9,"Labbes",'fr');
INSERT INTO category(id,name,lang) VALUES(10,"Limicoles",'fr');
INSERT INTO category(id,name,lang) VALUES(11,"Martinets et hirondelles",'fr');
INSERT INTO category(id,name,lang) VALUES(12,"Mouettes, goéland, fulmars",'fr');
INSERT INTO category(id,name,lang) VALUES(13,"passereaux",'fr');
INSERT INTO category(id,name,lang) VALUES(14,"Pics",'fr');
INSERT INTO category(id,name,lang) VALUES(15,"Pigeons et tourterelles",'fr');
INSERT INTO category(id,name,lang) VALUES(16,"Pingouins, guillemots, macareux",'fr');
INSERT INTO category(id,name,lang) VALUES(17,"Plongeons",'fr');
INSERT INTO category(id,name,lang) VALUES(18,"Râles, marouettes, poules d'eau",'fr');
INSERT INTO category(id,name,lang) VALUES(19,"Rapaces",'fr');
INSERT INTO category(id,name,lang) VALUES(20,"Sternes",'fr');
