#/bin/bash
cp audio/accenteur_alpin/59425.mp3 src_audio/accenteur_alpin
cp audio/accenteur_alpin/59425.mp3.properties src_audio/accenteur_alpin
cp audio/accenteur_alpin/83634.mp3 src_audio/accenteur_alpin
cp audio/accenteur_alpin/83634.mp3.properties src_audio/accenteur_alpin
cp audio/accenteur_mouchet/109863.mp3 src_audio/accenteur_mouchet
cp audio/accenteur_mouchet/109863.mp3.properties src_audio/accenteur_mouchet
cp audio/accenteur_mouchet/27116.mp3 src_audio/accenteur_mouchet
cp audio/accenteur_mouchet/27116.mp3.properties src_audio/accenteur_mouchet
cp audio/accenteur_mouchet/41222.mp3 src_audio/accenteur_mouchet
cp audio/accenteur_mouchet/41222.mp3.properties src_audio/accenteur_mouchet
cp audio/aigle_royal/110501.mp3 src_audio/aigle_royal
cp audio/aigle_royal/110501.mp3.properties src_audio/aigle_royal
cp audio/aigrette_a_gorge_blanche/118118.mp3 src_audio/aigrette_a_gorge_blanche
cp audio/aigrette_a_gorge_blanche/118118.mp3.properties src_audio/aigrette_a_gorge_blanche
cp audio/aigrette_garzette/107096.mp3 src_audio/aigrette_garzette
cp audio/aigrette_garzette/107096.mp3.properties src_audio/aigrette_garzette
cp audio/aigrette_garzette/26873.mp3 src_audio/aigrette_garzette
cp audio/aigrette_garzette/26873.mp3.properties src_audio/aigrette_garzette
cp audio/aigrette_garzette/35235.mp3 src_audio/aigrette_garzette
cp audio/aigrette_garzette/35235.mp3.properties src_audio/aigrette_garzette
cp audio/alouette_calandre/43663.mp3 src_audio/alouette_calandre
cp audio/alouette_calandre/43663.mp3.properties src_audio/alouette_calandre
cp audio/alouette_calandrelle/105404.mp3 src_audio/alouette_calandrelle
cp audio/alouette_calandrelle/105404.mp3.properties src_audio/alouette_calandrelle
cp audio/alouette_calandrelle/19687.mp3 src_audio/alouette_calandrelle
cp audio/alouette_calandrelle/19687.mp3.properties src_audio/alouette_calandrelle
cp audio/alouette_des_champs/114459.mp3 src_audio/alouette_des_champs
cp audio/alouette_des_champs/114459.mp3.properties src_audio/alouette_des_champs
cp audio/alouette_des_champs/25715.mp3 src_audio/alouette_des_champs
cp audio/alouette_des_champs/25715.mp3.properties src_audio/alouette_des_champs
cp audio/alouette_des_champs/83608.mp3 src_audio/alouette_des_champs
cp audio/alouette_des_champs/83608.mp3.properties src_audio/alouette_des_champs
cp audio/alouette_hausse-col/113144.mp3 src_audio/alouette_hausse-col
cp audio/alouette_hausse-col/113144.mp3.properties src_audio/alouette_hausse-col
cp audio/alouette_hausse-col/1201.mp3 src_audio/alouette_hausse-col
cp audio/alouette_hausse-col/1201.mp3.properties src_audio/alouette_hausse-col
cp audio/alouette_hausse-col/53791.mp3 src_audio/alouette_hausse-col
cp audio/alouette_hausse-col/53791.mp3.properties src_audio/alouette_hausse-col
cp audio/alouette_lulu/25774.mp3 src_audio/alouette_lulu
cp audio/alouette_lulu/25774.mp3.properties src_audio/alouette_lulu
cp audio/alouette_lulu/36288.mp3 src_audio/alouette_lulu
cp audio/alouette_lulu/36288.mp3.properties src_audio/alouette_lulu
cp audio/alouette_lulu/83024.mp3 src_audio/alouette_lulu
cp audio/alouette_lulu/83024.mp3.properties src_audio/alouette_lulu
cp audio/arlequin_plongeur/83951.mp3 src_audio/arlequin_plongeur
cp audio/arlequin_plongeur/83951.mp3.properties src_audio/arlequin_plongeur
cp audio/arlequin_plongeur/83953.mp3 src_audio/arlequin_plongeur
cp audio/arlequin_plongeur/83953.mp3.properties src_audio/arlequin_plongeur
cp audio/autour_des_palombes/27024.mp3 src_audio/autour_des_palombes
cp audio/autour_des_palombes/27024.mp3.properties src_audio/autour_des_palombes
cp audio/avocette_elegante/42552.mp3 src_audio/avocette_elegante
cp audio/avocette_elegante/42552.mp3.properties src_audio/avocette_elegante
cp audio/avocette_elegante/67413.mp3 src_audio/avocette_elegante
cp audio/avocette_elegante/67413.mp3.properties src_audio/avocette_elegante
cp audio/balbuzard_pecheur/118482.mp3 src_audio/balbuzard_pecheur
cp audio/balbuzard_pecheur/118482.mp3.properties src_audio/balbuzard_pecheur
cp audio/balbuzard_pecheur/70475.mp3 src_audio/balbuzard_pecheur
cp audio/balbuzard_pecheur/70475.mp3.properties src_audio/balbuzard_pecheur
cp audio/barge_a_queue_noire/42435.mp3 src_audio/barge_a_queue_noire
cp audio/barge_a_queue_noire/42435.mp3.properties src_audio/barge_a_queue_noire
cp audio/barge_a_queue_noire/53635.mp3 src_audio/barge_a_queue_noire
cp audio/barge_a_queue_noire/53635.mp3.properties src_audio/barge_a_queue_noire
cp audio/barge_a_queue_noire/57909.mp3 src_audio/barge_a_queue_noire
cp audio/barge_a_queue_noire/57909.mp3.properties src_audio/barge_a_queue_noire
cp audio/barge_rousse/107882.mp3 src_audio/barge_rousse
cp audio/barge_rousse/107882.mp3.properties src_audio/barge_rousse
cp audio/barge_rousse/25655.mp3 src_audio/barge_rousse
cp audio/barge_rousse/25655.mp3.properties src_audio/barge_rousse
cp audio/barge_rousse/57836.mp3 src_audio/barge_rousse
cp audio/barge_rousse/57836.mp3.properties src_audio/barge_rousse
cp audio/becasseau_cocorli/25830.mp3 src_audio/becasseau_cocorli
cp audio/becasseau_cocorli/25830.mp3.properties src_audio/becasseau_cocorli
cp audio/becasseau_de_temminck/106532.mp3 src_audio/becasseau_de_temminck
cp audio/becasseau_de_temminck/106532.mp3.properties src_audio/becasseau_de_temminck
cp audio/becasseau_de_temminck/24930.mp3 src_audio/becasseau_de_temminck
cp audio/becasseau_de_temminck/24930.mp3.properties src_audio/becasseau_de_temminck
cp audio/becasseau_de_temminck/87127.mp3 src_audio/becasseau_de_temminck
cp audio/becasseau_de_temminck/87127.mp3.properties src_audio/becasseau_de_temminck
cp audio/becasseau_falcinelle/106617.mp3 src_audio/becasseau_falcinelle
cp audio/becasseau_falcinelle/106617.mp3.properties src_audio/becasseau_falcinelle
cp audio/becasseau_falcinelle/58590.mp3 src_audio/becasseau_falcinelle
cp audio/becasseau_falcinelle/58590.mp3.properties src_audio/becasseau_falcinelle
cp audio/becasseau_maubeche/25617.mp3 src_audio/becasseau_maubeche
cp audio/becasseau_maubeche/25617.mp3.properties src_audio/becasseau_maubeche
cp audio/becasseau_maubeche/25618.mp3 src_audio/becasseau_maubeche
cp audio/becasseau_maubeche/25618.mp3.properties src_audio/becasseau_maubeche
cp audio/becasseau_minute/99967.mp3 src_audio/becasseau_minute
cp audio/becasseau_minute/99967.mp3.properties src_audio/becasseau_minute
cp audio/becasseau_sanderling/109324.mp3 src_audio/becasseau_sanderling
cp audio/becasseau_sanderling/109324.mp3.properties src_audio/becasseau_sanderling
cp audio/becasseau_sanderling/59506.mp3 src_audio/becasseau_sanderling
cp audio/becasseau_sanderling/59506.mp3.properties src_audio/becasseau_sanderling
cp audio/becasseau_variable/118363.mp3 src_audio/becasseau_variable
cp audio/becasseau_variable/118363.mp3.properties src_audio/becasseau_variable
cp audio/becasseau_variable/64738.mp3 src_audio/becasseau_variable
cp audio/becasseau_variable/64738.mp3.properties src_audio/becasseau_variable
cp audio/becasseau_violet/29897.mp3 src_audio/becasseau_violet
cp audio/becasseau_violet/29897.mp3.properties src_audio/becasseau_violet
cp audio/becasse_des_bois/27078.mp3 src_audio/becasse_des_bois
cp audio/becasse_des_bois/27078.mp3.properties src_audio/becasse_des_bois
cp audio/becasse_des_bois/36985.mp3 src_audio/becasse_des_bois
cp audio/becasse_des_bois/36985.mp3.properties src_audio/becasse_des_bois
cp audio/becasse_des_bois/84270.mp3 src_audio/becasse_des_bois
cp audio/becasse_des_bois/84270.mp3.properties src_audio/becasse_des_bois
cp audio/becassine_des_marais/36486.mp3 src_audio/becassine_des_marais
cp audio/becassine_des_marais/36486.mp3.properties src_audio/becassine_des_marais
cp audio/becassine_des_marais/76831.mp3 src_audio/becassine_des_marais
cp audio/becassine_des_marais/76831.mp3.properties src_audio/becassine_des_marais
cp audio/becassine_double/27083.mp3 src_audio/becassine_double
cp audio/becassine_double/27083.mp3.properties src_audio/becassine_double
cp audio/becassine_double/83238.mp3 src_audio/becassine_double
cp audio/becassine_double/83238.mp3.properties src_audio/becassine_double
cp audio/becassine_sourde/40491.mp3 src_audio/becassine_sourde
cp audio/becassine_sourde/40491.mp3.properties src_audio/becassine_sourde
cp audio/becassine_sourde/99131.mp3 src_audio/becassine_sourde
cp audio/becassine_sourde/99131.mp3.properties src_audio/becassine_sourde
cp audio/bec-croise_bifascie/15164.mp3 src_audio/bec-croise_bifascie
cp audio/bec-croise_bifascie/15164.mp3.properties src_audio/bec-croise_bifascie
cp audio/bec-croise_bifascie/29609.mp3 src_audio/bec-croise_bifascie
cp audio/bec-croise_bifascie/29609.mp3.properties src_audio/bec-croise_bifascie
cp audio/bec-croise_bifascie/87172.mp3 src_audio/bec-croise_bifascie
cp audio/bec-croise_bifascie/87172.mp3.properties src_audio/bec-croise_bifascie
cp audio/bec-croise_des_sapins/14392.mp3 src_audio/bec-croise_des_sapins
cp audio/bec-croise_des_sapins/14392.mp3.properties src_audio/bec-croise_des_sapins
cp audio/bec-croise_des_sapins/25806.mp3 src_audio/bec-croise_des_sapins
cp audio/bec-croise_des_sapins/25806.mp3.properties src_audio/bec-croise_des_sapins
cp audio/bec-croise_des_sapins/33944.mp3 src_audio/bec-croise_des_sapins
cp audio/bec-croise_des_sapins/33944.mp3.properties src_audio/bec-croise_des_sapins
cp audio/bec-croise_perroquet/108563.mp3 src_audio/bec-croise_perroquet
cp audio/bec-croise_perroquet/108563.mp3.properties src_audio/bec-croise_perroquet
cp audio/bec-croise_perroquet/84219.mp3 src_audio/bec-croise_perroquet
cp audio/bec-croise_perroquet/84219.mp3.properties src_audio/bec-croise_perroquet
cp audio/bec-croise_perroquet/98141.mp3 src_audio/bec-croise_perroquet
cp audio/bec-croise_perroquet/98141.mp3.properties src_audio/bec-croise_perroquet
cp audio/bergeronnette_citrine/35462.mp3 src_audio/bergeronnette_citrine
cp audio/bergeronnette_citrine/35462.mp3.properties src_audio/bergeronnette_citrine
cp audio/bergeronnette_citrine/43628.mp3 src_audio/bergeronnette_citrine
cp audio/bergeronnette_citrine/43628.mp3.properties src_audio/bergeronnette_citrine
cp audio/bergeronnette_citrine/68750.mp3 src_audio/bergeronnette_citrine
cp audio/bergeronnette_citrine/68750.mp3.properties src_audio/bergeronnette_citrine
cp audio/bergeronnette_des_ruisseaux/109726.mp3 src_audio/bergeronnette_des_ruisseaux
cp audio/bergeronnette_des_ruisseaux/109726.mp3.properties src_audio/bergeronnette_des_ruisseaux
cp audio/bergeronnette_des_ruisseaux/25538.mp3 src_audio/bergeronnette_des_ruisseaux
cp audio/bergeronnette_des_ruisseaux/25538.mp3.properties src_audio/bergeronnette_des_ruisseaux
cp audio/bergeronnette_des_ruisseaux/27017.mp3 src_audio/bergeronnette_des_ruisseaux
cp audio/bergeronnette_des_ruisseaux/27017.mp3.properties src_audio/bergeronnette_des_ruisseaux
cp audio/bergeronnette_grise/27021.mp3 src_audio/bergeronnette_grise
cp audio/bergeronnette_grise/27021.mp3.properties src_audio/bergeronnette_grise
cp audio/bergeronnette_grise/35533.mp3 src_audio/bergeronnette_grise
cp audio/bergeronnette_grise/35533.mp3.properties src_audio/bergeronnette_grise
cp audio/bergeronnette_grise/67484.mp3 src_audio/bergeronnette_grise
cp audio/bergeronnette_grise/67484.mp3.properties src_audio/bergeronnette_grise
cp audio/bergeronnette_printaniere/25098.mp3 src_audio/bergeronnette_printaniere
cp audio/bergeronnette_printaniere/25098.mp3.properties src_audio/bergeronnette_printaniere
cp audio/bergeronnette_printaniere/32096.mp3 src_audio/bergeronnette_printaniere
cp audio/bergeronnette_printaniere/32096.mp3.properties src_audio/bergeronnette_printaniere
cp audio/bergeronnette_printaniere/39391.mp3 src_audio/bergeronnette_printaniere
cp audio/bergeronnette_printaniere/39391.mp3.properties src_audio/bergeronnette_printaniere
cp audio/bernache_a_cou_roux/101103.mp3 src_audio/bernache_a_cou_roux
cp audio/bernache_a_cou_roux/101103.mp3.properties src_audio/bernache_a_cou_roux
cp audio/bernache_cravant/66132.mp3 src_audio/bernache_cravant
cp audio/bernache_cravant/66132.mp3.properties src_audio/bernache_cravant
cp audio/bernache_du_canada/27173.mp3 src_audio/bernache_du_canada
cp audio/bernache_du_canada/27173.mp3.properties src_audio/bernache_du_canada
cp audio/bernache_du_canada/30276.mp3 src_audio/bernache_du_canada
cp audio/bernache_du_canada/30276.mp3.properties src_audio/bernache_du_canada
cp audio/bernache_du_canada/61893.mp3 src_audio/bernache_du_canada
cp audio/bernache_du_canada/61893.mp3.properties src_audio/bernache_du_canada
cp audio/bernache_nonnette/113452.mp3 src_audio/bernache_nonnette
cp audio/bernache_nonnette/113452.mp3.properties src_audio/bernache_nonnette
cp audio/bernache_nonnette/99461.mp3 src_audio/bernache_nonnette
cp audio/bernache_nonnette/99461.mp3.properties src_audio/bernache_nonnette
cp audio/bihoreau_gris/110872.mp3 src_audio/bihoreau_gris
cp audio/bihoreau_gris/110872.mp3.properties src_audio/bihoreau_gris
cp audio/bihoreau_gris/50331.mp3 src_audio/bihoreau_gris
cp audio/bihoreau_gris/50331.mp3.properties src_audio/bihoreau_gris
cp audio/bihoreau_gris/60558.mp3 src_audio/bihoreau_gris
cp audio/bihoreau_gris/60558.mp3.properties src_audio/bihoreau_gris
cp audio/blongios_nain/35967.mp3 src_audio/blongios_nain
cp audio/blongios_nain/35967.mp3.properties src_audio/blongios_nain
cp audio/bouscarle_de_cetti/65566.mp3 src_audio/bouscarle_de_cetti
cp audio/bouscarle_de_cetti/65566.mp3.properties src_audio/bouscarle_de_cetti
cp audio/bouvreuil_pivoine/112839.mp3 src_audio/bouvreuil_pivoine
cp audio/bouvreuil_pivoine/112839.mp3.properties src_audio/bouvreuil_pivoine
cp audio/bouvreuil_pivoine/113691.mp3 src_audio/bouvreuil_pivoine
cp audio/bouvreuil_pivoine/113691.mp3.properties src_audio/bouvreuil_pivoine
cp audio/bouvreuil_pivoine/47921.mp3 src_audio/bouvreuil_pivoine
cp audio/bouvreuil_pivoine/47921.mp3.properties src_audio/bouvreuil_pivoine
cp audio/bruant_des_neiges/25167.mp3 src_audio/bruant_des_neiges
cp audio/bruant_des_neiges/25167.mp3.properties src_audio/bruant_des_neiges
cp audio/bruant_des_neiges/65888.mp3 src_audio/bruant_des_neiges
cp audio/bruant_des_neiges/65888.mp3.properties src_audio/bruant_des_neiges
cp audio/bruant_des_neiges/97645.mp3 src_audio/bruant_des_neiges
cp audio/bruant_des_neiges/97645.mp3.properties src_audio/bruant_des_neiges
cp audio/bruant_des_roseaux/26024.mp3 src_audio/bruant_des_roseaux
cp audio/bruant_des_roseaux/26024.mp3.properties src_audio/bruant_des_roseaux
cp audio/bruant_des_roseaux/27690.mp3 src_audio/bruant_des_roseaux
cp audio/bruant_des_roseaux/27690.mp3.properties src_audio/bruant_des_roseaux
cp audio/bruant_fou/30102.mp3 src_audio/bruant_fou
cp audio/bruant_fou/30102.mp3.properties src_audio/bruant_fou
cp audio/bruant_fou/79892.mp3 src_audio/bruant_fou
cp audio/bruant_fou/79892.mp3.properties src_audio/bruant_fou
cp audio/bruant_lapon/113145.mp3 src_audio/bruant_lapon
cp audio/bruant_lapon/113145.mp3.properties src_audio/bruant_lapon
cp audio/bruant_lapon/58552.mp3 src_audio/bruant_lapon
cp audio/bruant_lapon/58552.mp3.properties src_audio/bruant_lapon
cp audio/bruant_lapon/58559.mp3 src_audio/bruant_lapon
cp audio/bruant_lapon/58559.mp3.properties src_audio/bruant_lapon
cp audio/bruant_melanocephale/118570.mp3 src_audio/bruant_melanocephale
cp audio/bruant_melanocephale/118570.mp3.properties src_audio/bruant_melanocephale
cp audio/bruant_ortolan/27581.mp3 src_audio/bruant_ortolan
cp audio/bruant_ortolan/27581.mp3.properties src_audio/bruant_ortolan
cp audio/bruant_ortolan/80705.mp3 src_audio/bruant_ortolan
cp audio/bruant_ortolan/80705.mp3.properties src_audio/bruant_ortolan
cp audio/bruant_proyer/25929.mp3 src_audio/bruant_proyer
cp audio/bruant_proyer/25929.mp3.properties src_audio/bruant_proyer
cp audio/bruant_proyer/71709.mp3 src_audio/bruant_proyer
cp audio/bruant_proyer/71709.mp3.properties src_audio/bruant_proyer
cp audio/bruant_zizi/29454.mp3 src_audio/bruant_zizi
cp audio/bruant_zizi/29454.mp3.properties src_audio/bruant_zizi
cp audio/bruant_zizi/49911.mp3 src_audio/bruant_zizi
cp audio/bruant_zizi/49911.mp3.properties src_audio/bruant_zizi
cp audio/busard_des_roseaux/112488.mp3 src_audio/busard_des_roseaux
cp audio/busard_des_roseaux/112488.mp3.properties src_audio/busard_des_roseaux
cp audio/busard_des_roseaux/69852.mp3 src_audio/busard_des_roseaux
cp audio/busard_des_roseaux/69852.mp3.properties src_audio/busard_des_roseaux
cp audio/buse_pattue/106027.mp3 src_audio/buse_pattue
cp audio/buse_pattue/106027.mp3.properties src_audio/buse_pattue
cp audio/buse_variable/118356.mp3 src_audio/buse_variable
cp audio/buse_variable/118356.mp3.properties src_audio/buse_variable
cp audio/buse_variable/30430.mp3 src_audio/buse_variable
cp audio/buse_variable/30430.mp3.properties src_audio/buse_variable
cp audio/buse_variable/77238.mp3 src_audio/buse_variable
cp audio/buse_variable/77238.mp3.properties src_audio/buse_variable
cp audio/buse_variable/87679.mp3 src_audio/buse_variable
cp audio/buse_variable/87679.mp3.properties src_audio/buse_variable
cp audio/butor_etoile/107276.mp3 src_audio/butor_etoile
cp audio/butor_etoile/107276.mp3.properties src_audio/butor_etoile
cp audio/butor_etoile/42541.mp3 src_audio/butor_etoile
cp audio/butor_etoile/42541.mp3.properties src_audio/butor_etoile
cp audio/caille_des_bles/27535.mp3 src_audio/caille_des_bles
cp audio/caille_des_bles/27535.mp3.properties src_audio/caille_des_bles
cp audio/caille_des_bles/95803.mp3 src_audio/caille_des_bles
cp audio/caille_des_bles/95803.mp3.properties src_audio/caille_des_bles
cp audio/canard_chipeau/13736.mp3 src_audio/canard_chipeau
cp audio/canard_chipeau/13736.mp3.properties src_audio/canard_chipeau
cp audio/canard_chipeau/26959.mp3 src_audio/canard_chipeau
cp audio/canard_chipeau/26959.mp3.properties src_audio/canard_chipeau
cp audio/canard_colvert/26966.mp3 src_audio/canard_colvert
cp audio/canard_colvert/26966.mp3.properties src_audio/canard_colvert
cp audio/canard_colvert/26967.mp3 src_audio/canard_colvert
cp audio/canard_colvert/26967.mp3.properties src_audio/canard_colvert
cp audio/canard_colvert/56301.mp3 src_audio/canard_colvert
cp audio/canard_colvert/56301.mp3.properties src_audio/canard_colvert
cp audio/canard_mandarin/97013.mp3 src_audio/canard_mandarin
cp audio/canard_mandarin/97013.mp3.properties src_audio/canard_mandarin
cp audio/canard_pilet/44626.mp3 src_audio/canard_pilet
cp audio/canard_pilet/44626.mp3.properties src_audio/canard_pilet
cp audio/canard_siffleur/65796.mp3 src_audio/canard_siffleur
cp audio/canard_siffleur/65796.mp3.properties src_audio/canard_siffleur
cp audio/canard_siffleur/83877.mp3 src_audio/canard_siffleur
cp audio/canard_siffleur/83877.mp3.properties src_audio/canard_siffleur
cp audio/canard_souchet/42545.mp3 src_audio/canard_souchet
cp audio/canard_souchet/42545.mp3.properties src_audio/canard_souchet
cp audio/canard_souchet/75991.mp3 src_audio/canard_souchet
cp audio/canard_souchet/75991.mp3.properties src_audio/canard_souchet
cp audio/cassenoix_mouchete/20199.mp3 src_audio/cassenoix_mouchete
cp audio/cassenoix_mouchete/20199.mp3.properties src_audio/cassenoix_mouchete
cp audio/cassenoix_mouchete/40968.mp3 src_audio/cassenoix_mouchete
cp audio/cassenoix_mouchete/40968.mp3.properties src_audio/cassenoix_mouchete
cp audio/chardonneret_elegant/34678.mp3 src_audio/chardonneret_elegant
cp audio/chardonneret_elegant/34678.mp3.properties src_audio/chardonneret_elegant
cp audio/chardonneret_elegant/77402.mp3 src_audio/chardonneret_elegant
cp audio/chardonneret_elegant/77402.mp3.properties src_audio/chardonneret_elegant
cp audio/chevalier_aboyeur/35682.mp3 src_audio/chevalier_aboyeur
cp audio/chevalier_aboyeur/35682.mp3.properties src_audio/chevalier_aboyeur
cp audio/chevalier_aboyeur/36385.mp3 src_audio/chevalier_aboyeur
cp audio/chevalier_aboyeur/36385.mp3.properties src_audio/chevalier_aboyeur
cp audio/chevalier_aboyeur/39258.mp3 src_audio/chevalier_aboyeur
cp audio/chevalier_aboyeur/39258.mp3.properties src_audio/chevalier_aboyeur
cp audio/chevalier_arlequin/37601.mp3 src_audio/chevalier_arlequin
cp audio/chevalier_arlequin/37601.mp3.properties src_audio/chevalier_arlequin
cp audio/chevalier_arlequin/99139.mp3 src_audio/chevalier_arlequin
cp audio/chevalier_arlequin/99139.mp3.properties src_audio/chevalier_arlequin
cp audio/chevalier_arlequin/99930.mp3 src_audio/chevalier_arlequin
cp audio/chevalier_arlequin/99930.mp3.properties src_audio/chevalier_arlequin
cp audio/chevalier_cul-blanc/37505.mp3 src_audio/chevalier_cul-blanc
cp audio/chevalier_cul-blanc/37505.mp3.properties src_audio/chevalier_cul-blanc
cp audio/chevalier_cul-blanc/38635.mp3 src_audio/chevalier_cul-blanc
cp audio/chevalier_cul-blanc/38635.mp3.properties src_audio/chevalier_cul-blanc
cp audio/chevalier_cul-blanc/90460.mp3 src_audio/chevalier_cul-blanc
cp audio/chevalier_cul-blanc/90460.mp3.properties src_audio/chevalier_cul-blanc
cp audio/chevalier_gambette/25091.mp3 src_audio/chevalier_gambette
cp audio/chevalier_gambette/25091.mp3.properties src_audio/chevalier_gambette
cp audio/chevalier_gambette/28932.mp3 src_audio/chevalier_gambette
cp audio/chevalier_gambette/28932.mp3.properties src_audio/chevalier_gambette
cp audio/chevalier_gambette/43817.mp3 src_audio/chevalier_gambette
cp audio/chevalier_gambette/43817.mp3.properties src_audio/chevalier_gambette
cp audio/chevalier_gambette/99931.mp3 src_audio/chevalier_gambette
cp audio/chevalier_gambette/99931.mp3.properties src_audio/chevalier_gambette
cp audio/chevalier_guignette/29679.mp3 src_audio/chevalier_guignette
cp audio/chevalier_guignette/29679.mp3.properties src_audio/chevalier_guignette
cp audio/chevalier_guignette/99966.mp3 src_audio/chevalier_guignette
cp audio/chevalier_guignette/99966.mp3.properties src_audio/chevalier_guignette
cp audio/chevalier_stagnatile/35716.mp3 src_audio/chevalier_stagnatile
cp audio/chevalier_stagnatile/35716.mp3.properties src_audio/chevalier_stagnatile
cp audio/chevalier_stagnatile/91144.mp3 src_audio/chevalier_stagnatile
cp audio/chevalier_stagnatile/91144.mp3.properties src_audio/chevalier_stagnatile
cp audio/chevalier_stagnatile/99934.mp3 src_audio/chevalier_stagnatile
cp audio/chevalier_stagnatile/99934.mp3.properties src_audio/chevalier_stagnatile
cp audio/chevalier_sylvain/25123.mp3 src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/25123.mp3.properties src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/35567.mp3 src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/35567.mp3.properties src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/83245.mp3 src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/83245.mp3.properties src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/99958.mp3 src_audio/chevalier_sylvain
cp audio/chevalier_sylvain/99958.mp3.properties src_audio/chevalier_sylvain
cp audio/cheveche_d_athena/46452.mp3 src_audio/cheveche_d_athena
cp audio/cheveche_d_athena/46452.mp3.properties src_audio/cheveche_d_athena
cp audio/cheveche_d_athena/75862.mp3 src_audio/cheveche_d_athena
cp audio/cheveche_d_athena/75862.mp3.properties src_audio/cheveche_d_athena
cp audio/chevechette_d_europe/26690.mp3 src_audio/chevechette_d_europe
cp audio/chevechette_d_europe/26690.mp3.properties src_audio/chevechette_d_europe
cp audio/chevechette_d_europe/62717.mp3 src_audio/chevechette_d_europe
cp audio/chevechette_d_europe/62717.mp3.properties src_audio/chevechette_d_europe
cp audio/chocard_a_bec_jaune/30392.mp3 src_audio/chocard_a_bec_jaune
cp audio/chocard_a_bec_jaune/30392.mp3.properties src_audio/chocard_a_bec_jaune
cp audio/chocard_a_bec_jaune/46570.mp3 src_audio/chocard_a_bec_jaune
cp audio/chocard_a_bec_jaune/46570.mp3.properties src_audio/chocard_a_bec_jaune
cp audio/chocard_a_bec_jaune/89972.mp3 src_audio/chocard_a_bec_jaune
cp audio/chocard_a_bec_jaune/89972.mp3.properties src_audio/chocard_a_bec_jaune
cp audio/choucas_des_tours/113591.mp3 src_audio/choucas_des_tours
cp audio/choucas_des_tours/113591.mp3.properties src_audio/choucas_des_tours
cp audio/choucas_des_tours/121693.mp3 src_audio/choucas_des_tours
cp audio/choucas_des_tours/121693.mp3.properties src_audio/choucas_des_tours
cp audio/choucas_des_tours/28070.mp3 src_audio/choucas_des_tours
cp audio/choucas_des_tours/28070.mp3.properties src_audio/choucas_des_tours
cp audio/chouette_de_l_oural/26856.mp3 src_audio/chouette_de_l_oural
cp audio/chouette_de_l_oural/26856.mp3.properties src_audio/chouette_de_l_oural
cp audio/chouette_de_l_oural/75823.mp3 src_audio/chouette_de_l_oural
cp audio/chouette_de_l_oural/75823.mp3.properties src_audio/chouette_de_l_oural
cp audio/chouette_de_tengmalm/110185.mp3 src_audio/chouette_de_tengmalm
cp audio/chouette_de_tengmalm/110185.mp3.properties src_audio/chouette_de_tengmalm
cp audio/chouette_de_tengmalm/17769.mp3 src_audio/chouette_de_tengmalm
cp audio/chouette_de_tengmalm/17769.mp3.properties src_audio/chouette_de_tengmalm
cp audio/chouette_eperviere/57837.mp3 src_audio/chouette_eperviere
cp audio/chouette_eperviere/57837.mp3.properties src_audio/chouette_eperviere
cp audio/chouette_eperviere/67157.mp3 src_audio/chouette_eperviere
cp audio/chouette_eperviere/67157.mp3.properties src_audio/chouette_eperviere
cp audio/chouette_eperviere/70086.mp3 src_audio/chouette_eperviere
cp audio/chouette_eperviere/70086.mp3.properties src_audio/chouette_eperviere
cp audio/chouette_hulotte/26867.mp3 src_audio/chouette_hulotte
cp audio/chouette_hulotte/26867.mp3.properties src_audio/chouette_hulotte
cp audio/cigogne_blanche/75759.mp3 src_audio/cigogne_blanche
cp audio/cigogne_blanche/75759.mp3.properties src_audio/cigogne_blanche
cp audio/cincle_plongeur/29879.mp3 src_audio/cincle_plongeur
cp audio/cincle_plongeur/29879.mp3.properties src_audio/cincle_plongeur
cp audio/cincle_plongeur/72764.mp3 src_audio/cincle_plongeur
cp audio/cincle_plongeur/72764.mp3.properties src_audio/cincle_plongeur
cp audio/circaete_jean-le-blanc/28958.mp3 src_audio/circaete_jean-le-blanc
cp audio/circaete_jean-le-blanc/28958.mp3.properties src_audio/circaete_jean-le-blanc
cp audio/circaete_jean-le-blanc/61261.mp3 src_audio/circaete_jean-le-blanc
cp audio/circaete_jean-le-blanc/61261.mp3.properties src_audio/circaete_jean-le-blanc
cp audio/cisticole_des_joncs/44639.mp3 src_audio/cisticole_des_joncs
cp audio/cisticole_des_joncs/44639.mp3.properties src_audio/cisticole_des_joncs
cp audio/cisticole_des_joncs/95348.mp3 src_audio/cisticole_des_joncs
cp audio/cisticole_des_joncs/95348.mp3.properties src_audio/cisticole_des_joncs
cp audio/cochevis_huppe/120331.mp3 src_audio/cochevis_huppe
cp audio/cochevis_huppe/120331.mp3.properties src_audio/cochevis_huppe
cp audio/cochevis_huppe/30406.mp3 src_audio/cochevis_huppe
cp audio/cochevis_huppe/30406.mp3.properties src_audio/cochevis_huppe
cp audio/cochevis_huppe/75860.mp3 src_audio/cochevis_huppe
cp audio/cochevis_huppe/75860.mp3.properties src_audio/cochevis_huppe
cp audio/corbeau_freux/27145.mp3 src_audio/corbeau_freux
cp audio/corbeau_freux/27145.mp3.properties src_audio/corbeau_freux
cp audio/corbeau_freux/30279.mp3 src_audio/corbeau_freux
cp audio/corbeau_freux/30279.mp3.properties src_audio/corbeau_freux
cp audio/corbeau_freux/42637.mp3 src_audio/corbeau_freux
cp audio/corbeau_freux/42637.mp3.properties src_audio/corbeau_freux
cp audio/corneille_mantelee/28392.mp3 src_audio/corneille_mantelee
cp audio/corneille_mantelee/28392.mp3.properties src_audio/corneille_mantelee
cp audio/corneille_mantelee/31748.mp3 src_audio/corneille_mantelee
cp audio/corneille_mantelee/31748.mp3.properties src_audio/corneille_mantelee
cp audio/corneille_mantelee/42340.mp3 src_audio/corneille_mantelee
cp audio/corneille_mantelee/42340.mp3.properties src_audio/corneille_mantelee
cp audio/corneille_noire/121367.mp3 src_audio/corneille_noire
cp audio/corneille_noire/121367.mp3.properties src_audio/corneille_noire
cp audio/corneille_noire/29568.mp3 src_audio/corneille_noire
cp audio/corneille_noire/29568.mp3.properties src_audio/corneille_noire
cp audio/corneille_noire/96133.mp3 src_audio/corneille_noire
cp audio/corneille_noire/96133.mp3.properties src_audio/corneille_noire
cp audio/coucou_geai/29809.mp3 src_audio/coucou_geai
cp audio/coucou_geai/29809.mp3.properties src_audio/coucou_geai
cp audio/coucou_geai/32885.mp3 src_audio/coucou_geai
cp audio/coucou_geai/32885.mp3.properties src_audio/coucou_geai
cp audio/coucou_gris/23966.mp3 src_audio/coucou_gris
cp audio/coucou_gris/23966.mp3.properties src_audio/coucou_gris
cp audio/coucou_gris/64889.mp3 src_audio/coucou_gris
cp audio/coucou_gris/64889.mp3.properties src_audio/coucou_gris
cp audio/courlis_cendre/34036.mp3 src_audio/courlis_cendre
cp audio/courlis_cendre/34036.mp3.properties src_audio/courlis_cendre
cp audio/courlis_cendre/42566.mp3 src_audio/courlis_cendre
cp audio/courlis_cendre/42566.mp3.properties src_audio/courlis_cendre
cp audio/courlis_cendre/42567.mp3 src_audio/courlis_cendre
cp audio/courlis_cendre/42567.mp3.properties src_audio/courlis_cendre
cp audio/courlis_corlieu/102862.mp3 src_audio/courlis_corlieu
cp audio/courlis_corlieu/102862.mp3.properties src_audio/courlis_corlieu
cp audio/courlis_corlieu/25156.mp3 src_audio/courlis_corlieu
cp audio/courlis_corlieu/25156.mp3.properties src_audio/courlis_corlieu
cp audio/courlis_corlieu/36348.mp3 src_audio/courlis_corlieu
cp audio/courlis_corlieu/36348.mp3.properties src_audio/courlis_corlieu
cp audio/crave_a_bec_rouge/106589.mp3 src_audio/crave_a_bec_rouge
cp audio/crave_a_bec_rouge/106589.mp3.properties src_audio/crave_a_bec_rouge
cp audio/crave_a_bec_rouge/30396.mp3 src_audio/crave_a_bec_rouge
cp audio/crave_a_bec_rouge/30396.mp3.properties src_audio/crave_a_bec_rouge
cp audio/cygne_chanteur/27172.mp3 src_audio/cygne_chanteur
cp audio/cygne_chanteur/27172.mp3.properties src_audio/cygne_chanteur
cp audio/cygne_chanteur/71165.mp3 src_audio/cygne_chanteur
cp audio/cygne_chanteur/71165.mp3.properties src_audio/cygne_chanteur
cp audio/cygne_tubercule/37572.mp3 src_audio/cygne_tubercule
cp audio/cygne_tubercule/37572.mp3.properties src_audio/cygne_tubercule
cp audio/durbec_des_sapins/15162.mp3 src_audio/durbec_des_sapins
cp audio/durbec_des_sapins/15162.mp3.properties src_audio/durbec_des_sapins
cp audio/durbec_des_sapins/15163.mp3 src_audio/durbec_des_sapins
cp audio/durbec_des_sapins/15163.mp3.properties src_audio/durbec_des_sapins
cp audio/echasse_blanche/113655.mp3 src_audio/echasse_blanche
cp audio/echasse_blanche/113655.mp3.properties src_audio/echasse_blanche
cp audio/echasse_blanche/28183.mp3 src_audio/echasse_blanche
cp audio/echasse_blanche/28183.mp3.properties src_audio/echasse_blanche
cp audio/echasse_blanche/77654.mp3 src_audio/echasse_blanche
cp audio/echasse_blanche/77654.mp3.properties src_audio/echasse_blanche
cp audio/effraie_des_clochers/102662.mp3 src_audio/effraie_des_clochers
cp audio/effraie_des_clochers/102662.mp3.properties src_audio/effraie_des_clochers
cp audio/effraie_des_clochers/29786.mp3 src_audio/effraie_des_clochers
cp audio/effraie_des_clochers/29786.mp3.properties src_audio/effraie_des_clochers
cp audio/eider_a_duvet/49814.mp3 src_audio/eider_a_duvet
cp audio/eider_a_duvet/49814.mp3.properties src_audio/eider_a_duvet
cp audio/eider_a_duvet/67130.mp3 src_audio/eider_a_duvet
cp audio/eider_a_duvet/67130.mp3.properties src_audio/eider_a_duvet
cp audio/elanion_blanc/95322.mp3 src_audio/elanion_blanc
cp audio/elanion_blanc/95322.mp3.properties src_audio/elanion_blanc
cp audio/engoulevent_d_europe/37735.mp3 src_audio/engoulevent_d_europe
cp audio/engoulevent_d_europe/37735.mp3.properties src_audio/engoulevent_d_europe
cp audio/engoulevent_d_europe/67220.mp3 src_audio/engoulevent_d_europe
cp audio/engoulevent_d_europe/67220.mp3.properties src_audio/engoulevent_d_europe
cp audio/epervier_d_europe/112187.mp3 src_audio/epervier_d_europe
cp audio/epervier_d_europe/112187.mp3.properties src_audio/epervier_d_europe
cp audio/epervier_d_europe/120729.mp3 src_audio/epervier_d_europe
cp audio/epervier_d_europe/120729.mp3.properties src_audio/epervier_d_europe
cp audio/erismature_rousse/109911.mp3 src_audio/erismature_rousse
cp audio/erismature_rousse/109911.mp3.properties src_audio/erismature_rousse
cp audio/erismature_rousse/53679.mp3 src_audio/erismature_rousse
cp audio/erismature_rousse/53679.mp3.properties src_audio/erismature_rousse
cp audio/etourneau_roselin/120494.mp3 src_audio/etourneau_roselin
cp audio/etourneau_roselin/120494.mp3.properties src_audio/etourneau_roselin
cp audio/etourneau_roselin/98654.mp3 src_audio/etourneau_roselin
cp audio/etourneau_roselin/98654.mp3.properties src_audio/etourneau_roselin
cp audio/etourneau_sansonnet/27154.mp3 src_audio/etourneau_sansonnet
cp audio/etourneau_sansonnet/27154.mp3.properties src_audio/etourneau_sansonnet
cp audio/etourneau_sansonnet/65446.mp3 src_audio/etourneau_sansonnet
cp audio/etourneau_sansonnet/65446.mp3.properties src_audio/etourneau_sansonnet
cp audio/etourneau_unicolore/101937.mp3 src_audio/etourneau_unicolore
cp audio/etourneau_unicolore/101937.mp3.properties src_audio/etourneau_unicolore
cp audio/etourneau_unicolore/41257.mp3 src_audio/etourneau_unicolore
cp audio/etourneau_unicolore/41257.mp3.properties src_audio/etourneau_unicolore
cp audio/faisan_de_colchide/22692.mp3 src_audio/faisan_de_colchide
cp audio/faisan_de_colchide/22692.mp3.properties src_audio/faisan_de_colchide
cp audio/faisan_de_colchide/22694.mp3 src_audio/faisan_de_colchide
cp audio/faisan_de_colchide/22694.mp3.properties src_audio/faisan_de_colchide
cp audio/faisan_de_lady_amherst/111170.mp3 src_audio/faisan_de_lady_amherst
cp audio/faisan_de_lady_amherst/111170.mp3.properties src_audio/faisan_de_lady_amherst
cp audio/faisan_de_lady_amherst/37521.mp3 src_audio/faisan_de_lady_amherst
cp audio/faisan_de_lady_amherst/37521.mp3.properties src_audio/faisan_de_lady_amherst
cp audio/faisan_dore/18638.mp3 src_audio/faisan_dore
cp audio/faisan_dore/18638.mp3.properties src_audio/faisan_dore
cp audio/faisan_dore/40965.mp3 src_audio/faisan_dore
cp audio/faisan_dore/40965.mp3.properties src_audio/faisan_dore
cp audio/faucon_crecerelle/37451.mp3 src_audio/faucon_crecerelle
cp audio/faucon_crecerelle/37451.mp3.properties src_audio/faucon_crecerelle
cp audio/faucon_crecerelle/40770.mp3 src_audio/faucon_crecerelle
cp audio/faucon_crecerelle/40770.mp3.properties src_audio/faucon_crecerelle
cp audio/faucon_crecerellette/29067.mp3 src_audio/faucon_crecerellette
cp audio/faucon_crecerellette/29067.mp3.properties src_audio/faucon_crecerellette
cp audio/faucon_crecerellette/46107.mp3 src_audio/faucon_crecerellette
cp audio/faucon_crecerellette/46107.mp3.properties src_audio/faucon_crecerellette
cp audio/faucon_emerillon/65982.mp3 src_audio/faucon_emerillon
cp audio/faucon_emerillon/65982.mp3.properties src_audio/faucon_emerillon
cp audio/faucon_hobereau/109646.mp3 src_audio/faucon_hobereau
cp audio/faucon_hobereau/109646.mp3.properties src_audio/faucon_hobereau
cp audio/faucon_hobereau/90627.mp3 src_audio/faucon_hobereau
cp audio/faucon_hobereau/90627.mp3.properties src_audio/faucon_hobereau
cp audio/faucon_kobez/34559.mp3 src_audio/faucon_kobez
cp audio/faucon_kobez/34559.mp3.properties src_audio/faucon_kobez
cp audio/faucon_kobez/37581.mp3 src_audio/faucon_kobez
cp audio/faucon_kobez/37581.mp3.properties src_audio/faucon_kobez
cp audio/faucon_pelerin/44080.mp3 src_audio/faucon_pelerin
cp audio/faucon_pelerin/44080.mp3.properties src_audio/faucon_pelerin
cp audio/faucon_pelerin/90360.mp3 src_audio/faucon_pelerin
cp audio/faucon_pelerin/90360.mp3.properties src_audio/faucon_pelerin
cp audio/fauvette_a_lunettes/103568.mp3 src_audio/fauvette_a_lunettes
cp audio/fauvette_a_lunettes/103568.mp3.properties src_audio/fauvette_a_lunettes
cp audio/fauvette_a_lunettes/30173.mp3 src_audio/fauvette_a_lunettes
cp audio/fauvette_a_lunettes/30173.mp3.properties src_audio/fauvette_a_lunettes
cp audio/fauvette_a_tete_noire/25695.mp3 src_audio/fauvette_a_tete_noire
cp audio/fauvette_a_tete_noire/25695.mp3.properties src_audio/fauvette_a_tete_noire
cp audio/fauvette_a_tete_noire/62088.mp3 src_audio/fauvette_a_tete_noire
cp audio/fauvette_a_tete_noire/62088.mp3.properties src_audio/fauvette_a_tete_noire
cp audio/fauvette_a_tete_noire/77565.mp3 src_audio/fauvette_a_tete_noire
cp audio/fauvette_a_tete_noire/77565.mp3.properties src_audio/fauvette_a_tete_noire
cp audio/fauvette_babillarde/25096.mp3 src_audio/fauvette_babillarde
cp audio/fauvette_babillarde/25096.mp3.properties src_audio/fauvette_babillarde
cp audio/fauvette_babillarde/27140.mp3 src_audio/fauvette_babillarde
cp audio/fauvette_babillarde/27140.mp3.properties src_audio/fauvette_babillarde
cp audio/fauvette_des_jardins/25063.mp3 src_audio/fauvette_des_jardins
cp audio/fauvette_des_jardins/25063.mp3.properties src_audio/fauvette_des_jardins
cp audio/fauvette_eperviere/103379.mp3 src_audio/fauvette_eperviere
cp audio/fauvette_eperviere/103379.mp3.properties src_audio/fauvette_eperviere
cp audio/fauvette_eperviere/27127.mp3 src_audio/fauvette_eperviere
cp audio/fauvette_eperviere/27127.mp3.properties src_audio/fauvette_eperviere
cp audio/fauvette_grisette/25700.mp3 src_audio/fauvette_grisette
cp audio/fauvette_grisette/25700.mp3.properties src_audio/fauvette_grisette
cp audio/fauvette_grisette/34097.mp3 src_audio/fauvette_grisette
cp audio/fauvette_grisette/34097.mp3.properties src_audio/fauvette_grisette
cp audio/fauvette_grisette/35415.mp3 src_audio/fauvette_grisette
cp audio/fauvette_grisette/35415.mp3.properties src_audio/fauvette_grisette
cp audio/fauvette_melanocephale/29471.mp3 src_audio/fauvette_melanocephale
cp audio/fauvette_melanocephale/29471.mp3.properties src_audio/fauvette_melanocephale
cp audio/fauvette_melanocephale/30411.mp3 src_audio/fauvette_melanocephale
cp audio/fauvette_melanocephale/30411.mp3.properties src_audio/fauvette_melanocephale
cp audio/fauvette_melanocephale/78249.mp3 src_audio/fauvette_melanocephale
cp audio/fauvette_melanocephale/78249.mp3.properties src_audio/fauvette_melanocephale
cp audio/fauvette_orphee/107232.mp3 src_audio/fauvette_orphee
cp audio/fauvette_orphee/107232.mp3.properties src_audio/fauvette_orphee
cp audio/fauvette_orphee/78354.mp3 src_audio/fauvette_orphee
cp audio/fauvette_orphee/78354.mp3.properties src_audio/fauvette_orphee
cp audio/fauvette_passerinette/100771.mp3 src_audio/fauvette_passerinette
cp audio/fauvette_passerinette/100771.mp3.properties src_audio/fauvette_passerinette
cp audio/fauvette_passerinette/31738.mp3 src_audio/fauvette_passerinette
cp audio/fauvette_passerinette/31738.mp3.properties src_audio/fauvette_passerinette
cp audio/fauvette_pitchou/54111.mp3 src_audio/fauvette_pitchou
cp audio/fauvette_pitchou/54111.mp3.properties src_audio/fauvette_pitchou
cp audio/fauvette_pitchou/76866.mp3 src_audio/fauvette_pitchou
cp audio/fauvette_pitchou/76866.mp3.properties src_audio/fauvette_pitchou
cp audio/fauvette_sarde/31755.mp3 src_audio/fauvette_sarde
cp audio/fauvette_sarde/31755.mp3.properties src_audio/fauvette_sarde
cp audio/fauvette_sarde/38042.mp3 src_audio/fauvette_sarde
cp audio/fauvette_sarde/38042.mp3.properties src_audio/fauvette_sarde
cp audio/flamant_rose/37503.mp3 src_audio/flamant_rose
cp audio/flamant_rose/37503.mp3.properties src_audio/flamant_rose
cp audio/flamant_rose/97896.mp3 src_audio/flamant_rose
cp audio/flamant_rose/97896.mp3.properties src_audio/flamant_rose
cp audio/foulque_a_crete/75432.mp3 src_audio/foulque_a_crete
cp audio/foulque_a_crete/75432.mp3.properties src_audio/foulque_a_crete
cp audio/foulque_macroule/112698.mp3 src_audio/foulque_macroule
cp audio/foulque_macroule/112698.mp3.properties src_audio/foulque_macroule
cp audio/foulque_macroule/37445.mp3 src_audio/foulque_macroule
cp audio/foulque_macroule/37445.mp3.properties src_audio/foulque_macroule
cp audio/foulque_macroule/38637.mp3 src_audio/foulque_macroule
cp audio/foulque_macroule/38637.mp3.properties src_audio/foulque_macroule
cp audio/fuligule_milouin/100080.mp3 src_audio/fuligule_milouin
cp audio/fuligule_milouin/100080.mp3.properties src_audio/fuligule_milouin
cp audio/fuligule_milouin/100882.mp3 src_audio/fuligule_milouin
cp audio/fuligule_milouin/100882.mp3.properties src_audio/fuligule_milouin
cp audio/fuligule_milouinan/44265.mp3 src_audio/fuligule_milouinan
cp audio/fuligule_milouinan/44265.mp3.properties src_audio/fuligule_milouinan
cp audio/fuligule_morillon/83972.mp3 src_audio/fuligule_morillon
cp audio/fuligule_morillon/83972.mp3.properties src_audio/fuligule_morillon
cp audio/gallinule_poule-d_eau/104075.mp3 src_audio/gallinule_poule-d_eau
cp audio/gallinule_poule-d_eau/104075.mp3.properties src_audio/gallinule_poule-d_eau
cp audio/gallinule_poule-d_eau/26789.mp3 src_audio/gallinule_poule-d_eau
cp audio/gallinule_poule-d_eau/26789.mp3.properties src_audio/gallinule_poule-d_eau
cp audio/gallinule_poule-d_eau/30391.mp3 src_audio/gallinule_poule-d_eau
cp audio/gallinule_poule-d_eau/30391.mp3.properties src_audio/gallinule_poule-d_eau
cp audio/ganga_cata/101101.mp3 src_audio/ganga_cata
cp audio/ganga_cata/101101.mp3.properties src_audio/ganga_cata
cp audio/ganga_unibande/120502.mp3 src_audio/ganga_unibande
cp audio/ganga_unibande/120502.mp3.properties src_audio/ganga_unibande
cp audio/garrot_a_oeil_d_or/29031.mp3 src_audio/garrot_a_oeil_d_or
cp audio/garrot_a_oeil_d_or/29031.mp3.properties src_audio/garrot_a_oeil_d_or
cp audio/garrot_a_oeil_d_or/42334.mp3 src_audio/garrot_a_oeil_d_or
cp audio/garrot_a_oeil_d_or/42334.mp3.properties src_audio/garrot_a_oeil_d_or
cp audio/geai_des_chenes/30954.mp3 src_audio/geai_des_chenes
cp audio/geai_des_chenes/30954.mp3.properties src_audio/geai_des_chenes
cp audio/geai_des_chenes/46223.mp3 src_audio/geai_des_chenes
cp audio/geai_des_chenes/46223.mp3.properties src_audio/geai_des_chenes
cp audio/gelinotte_des_bois/26780.mp3 src_audio/gelinotte_des_bois
cp audio/gelinotte_des_bois/26780.mp3.properties src_audio/gelinotte_des_bois
cp audio/gelinotte_des_bois/75821.mp3 src_audio/gelinotte_des_bois
cp audio/gelinotte_des_bois/75821.mp3.properties src_audio/gelinotte_des_bois
cp audio/glareole_a_collier/111587.mp3 src_audio/glareole_a_collier
cp audio/glareole_a_collier/111587.mp3.properties src_audio/glareole_a_collier
cp audio/glareole_a_collier/98714.mp3 src_audio/glareole_a_collier
cp audio/glareole_a_collier/98714.mp3.properties src_audio/glareole_a_collier
cp audio/gobemouche_a_collier/78474.mp3 src_audio/gobemouche_a_collier
cp audio/gobemouche_a_collier/78474.mp3.properties src_audio/gobemouche_a_collier
cp audio/gobemouche_a_collier/87101.mp3 src_audio/gobemouche_a_collier
cp audio/gobemouche_a_collier/87101.mp3.properties src_audio/gobemouche_a_collier
cp audio/gobemouche_gris/27532.mp3 src_audio/gobemouche_gris
cp audio/gobemouche_gris/27532.mp3.properties src_audio/gobemouche_gris
cp audio/gobemouche_gris/65456.mp3 src_audio/gobemouche_gris
cp audio/gobemouche_gris/65456.mp3.properties src_audio/gobemouche_gris
cp audio/gobemouche_nain/26708.mp3 src_audio/gobemouche_nain
cp audio/gobemouche_nain/26708.mp3.properties src_audio/gobemouche_nain
cp audio/gobemouche_nain/40048.mp3 src_audio/gobemouche_nain
cp audio/gobemouche_nain/40048.mp3.properties src_audio/gobemouche_nain
cp audio/gobemouche_noir/25641.mp3 src_audio/gobemouche_noir
cp audio/gobemouche_noir/25641.mp3.properties src_audio/gobemouche_noir
cp audio/gobemouche_noir/27526.mp3 src_audio/gobemouche_noir
cp audio/gobemouche_noir/27526.mp3.properties src_audio/gobemouche_noir
cp audio/goeland_argente/40498.mp3 src_audio/goeland_argente
cp audio/goeland_argente/40498.mp3.properties src_audio/goeland_argente
cp audio/goeland_brun/87126.mp3 src_audio/goeland_brun
cp audio/goeland_brun/87126.mp3.properties src_audio/goeland_brun
cp audio/goeland_cendre/37449.mp3 src_audio/goeland_cendre
cp audio/goeland_cendre/37449.mp3.properties src_audio/goeland_cendre
cp audio/goeland_cendre/61891.mp3 src_audio/goeland_cendre
cp audio/goeland_cendre/61891.mp3.properties src_audio/goeland_cendre
cp audio/goeland_marin/59510.mp3 src_audio/goeland_marin
cp audio/goeland_marin/59510.mp3.properties src_audio/goeland_marin
cp audio/gorgebleue_a_miroir/109136.mp3 src_audio/gorgebleue_a_miroir
cp audio/gorgebleue_a_miroir/109136.mp3.properties src_audio/gorgebleue_a_miroir
cp audio/gorgebleue_a_miroir/27283.mp3 src_audio/gorgebleue_a_miroir
cp audio/gorgebleue_a_miroir/27283.mp3.properties src_audio/gorgebleue_a_miroir
cp audio/grand_corbeau/119597.mp3 src_audio/grand_corbeau
cp audio/grand_corbeau/119597.mp3.properties src_audio/grand_corbeau
cp audio/grand_corbeau/1199.mp3 src_audio/grand_corbeau
cp audio/grand_corbeau/1199.mp3.properties src_audio/grand_corbeau
cp audio/grand_corbeau/27147.mp3 src_audio/grand_corbeau
cp audio/grand_corbeau/27147.mp3.properties src_audio/grand_corbeau
cp audio/grand_cormoran/24917.mp3 src_audio/grand_cormoran
cp audio/grand_cormoran/24917.mp3.properties src_audio/grand_cormoran
cp audio/grand_cormoran/37544.mp3 src_audio/grand_cormoran
cp audio/grand_cormoran/37544.mp3.properties src_audio/grand_cormoran
cp audio/grand_cormoran/41949.mp3 src_audio/grand_cormoran
cp audio/grand_cormoran/41949.mp3.properties src_audio/grand_cormoran
cp audio/grand-duc_d_europe/121579.mp3 src_audio/grand-duc_d_europe
cp audio/grand-duc_d_europe/121579.mp3.properties src_audio/grand-duc_d_europe
cp audio/grand-duc_d_europe/26852.mp3 src_audio/grand-duc_d_europe
cp audio/grand-duc_d_europe/26852.mp3.properties src_audio/grand-duc_d_europe
cp audio/grande_aigrette/16349.mp3 src_audio/grande_aigrette
cp audio/grande_aigrette/16349.mp3.properties src_audio/grande_aigrette
cp audio/grande_aigrette/43121.mp3 src_audio/grande_aigrette
cp audio/grande_aigrette/43121.mp3.properties src_audio/grande_aigrette
cp audio/grande_aigrette/44629.mp3 src_audio/grande_aigrette
cp audio/grande_aigrette/44629.mp3.properties src_audio/grande_aigrette
cp audio/grand_gravelot/25076.mp3 src_audio/grand_gravelot
cp audio/grand_gravelot/25076.mp3.properties src_audio/grand_gravelot
cp audio/grand_gravelot/42571.mp3 src_audio/grand_gravelot
cp audio/grand_gravelot/42571.mp3.properties src_audio/grand_gravelot
cp audio/grand_harle/27186.mp3 src_audio/grand_harle
cp audio/grand_harle/27186.mp3.properties src_audio/grand_harle
cp audio/grand_harle/41152.mp3 src_audio/grand_harle
cp audio/grand_harle/41152.mp3.properties src_audio/grand_harle
cp audio/grand_labbe/57924.mp3 src_audio/grand_labbe
cp audio/grand_labbe/57924.mp3.properties src_audio/grand_labbe
cp audio/grand_tetras/33386.mp3 src_audio/grand_tetras
cp audio/grand_tetras/33386.mp3.properties src_audio/grand_tetras
cp audio/gravelot_a_collier_interrompu/100954.mp3 src_audio/gravelot_a_collier_interrompu
cp audio/gravelot_a_collier_interrompu/100954.mp3.properties src_audio/gravelot_a_collier_interrompu
cp audio/grebe_a_cou_noir/110082.mp3 src_audio/grebe_a_cou_noir
cp audio/grebe_a_cou_noir/110082.mp3.properties src_audio/grebe_a_cou_noir
cp audio/grebe_castagneux/24916.mp3 src_audio/grebe_castagneux
cp audio/grebe_castagneux/24916.mp3.properties src_audio/grebe_castagneux
cp audio/grebe_castagneux/26929.mp3 src_audio/grebe_castagneux
cp audio/grebe_castagneux/26929.mp3.properties src_audio/grebe_castagneux
cp audio/grebe_esclavon/103561.mp3 src_audio/grebe_esclavon
cp audio/grebe_esclavon/103561.mp3.properties src_audio/grebe_esclavon
cp audio/grebe_huppe/26935.mp3 src_audio/grebe_huppe
cp audio/grebe_huppe/26935.mp3.properties src_audio/grebe_huppe
cp audio/grebe_huppe/42551.mp3 src_audio/grebe_huppe
cp audio/grebe_huppe/42551.mp3.properties src_audio/grebe_huppe
cp audio/grebe_jougris/25577.mp3 src_audio/grebe_jougris
cp audio/grebe_jougris/25577.mp3.properties src_audio/grebe_jougris
cp audio/grebe_jougris/74734.mp3 src_audio/grebe_jougris
cp audio/grebe_jougris/74734.mp3.properties src_audio/grebe_jougris
cp audio/grimpereau_des_bois/25624.mp3 src_audio/grimpereau_des_bois
cp audio/grimpereau_des_bois/25624.mp3.properties src_audio/grimpereau_des_bois
cp audio/grimpereau_des_bois/25733.mp3 src_audio/grimpereau_des_bois
cp audio/grimpereau_des_bois/25733.mp3.properties src_audio/grimpereau_des_bois
cp audio/grimpereau_des_jardins/35074.mp3 src_audio/grimpereau_des_jardins
cp audio/grimpereau_des_jardins/35074.mp3.properties src_audio/grimpereau_des_jardins
cp audio/grive_draine/90373.mp3 src_audio/grive_draine
cp audio/grive_draine/90373.mp3.properties src_audio/grive_draine
cp audio/grive_litorne/120320.mp3 src_audio/grive_litorne
cp audio/grive_litorne/120320.mp3.properties src_audio/grive_litorne
cp audio/grive_litorne/43771.mp3 src_audio/grive_litorne
cp audio/grive_litorne/43771.mp3.properties src_audio/grive_litorne
cp audio/grive_litorne/52389.mp3 src_audio/grive_litorne
cp audio/grive_litorne/52389.mp3.properties src_audio/grive_litorne
cp audio/grive_mauvis/25083.mp3 src_audio/grive_mauvis
cp audio/grive_mauvis/25083.mp3.properties src_audio/grive_mauvis
cp audio/grive_mauvis/25117.mp3 src_audio/grive_mauvis
cp audio/grive_mauvis/25117.mp3.properties src_audio/grive_mauvis
cp audio/grive_mauvis/70127.mp3 src_audio/grive_mauvis
cp audio/grive_mauvis/70127.mp3.properties src_audio/grive_mauvis
cp audio/grive_mauvis/85973.mp3 src_audio/grive_mauvis
cp audio/grive_mauvis/85973.mp3.properties src_audio/grive_mauvis
cp audio/gros-bec_casse-noyaux/121318.mp3 src_audio/gros-bec_casse-noyaux
cp audio/gros-bec_casse-noyaux/121318.mp3.properties src_audio/gros-bec_casse-noyaux
cp audio/gros-bec_casse-noyaux/27102.mp3 src_audio/gros-bec_casse-noyaux
cp audio/gros-bec_casse-noyaux/27102.mp3.properties src_audio/gros-bec_casse-noyaux
cp audio/gros-bec_casse-noyaux/45343.mp3 src_audio/gros-bec_casse-noyaux
cp audio/gros-bec_casse-noyaux/45343.mp3.properties src_audio/gros-bec_casse-noyaux
cp audio/grue_cendree/120929.mp3 src_audio/grue_cendree
cp audio/grue_cendree/120929.mp3.properties src_audio/grue_cendree
cp audio/grue_cendree/40489.mp3 src_audio/grue_cendree
cp audio/grue_cendree/40489.mp3.properties src_audio/grue_cendree
cp audio/grue_cendree/71065.mp3 src_audio/grue_cendree
cp audio/grue_cendree/71065.mp3.properties src_audio/grue_cendree
cp audio/guepier_d_europe/109276.mp3 src_audio/guepier_d_europe
cp audio/guepier_d_europe/109276.mp3.properties src_audio/guepier_d_europe
cp audio/guepier_d_europe/75756.mp3 src_audio/guepier_d_europe
cp audio/guepier_d_europe/75756.mp3.properties src_audio/guepier_d_europe
cp audio/guepier_d_europe/97194.mp3 src_audio/guepier_d_europe
cp audio/guepier_d_europe/97194.mp3.properties src_audio/guepier_d_europe
cp audio/guifette_leucoptere/113609.mp3 src_audio/guifette_leucoptere
cp audio/guifette_leucoptere/113609.mp3.properties src_audio/guifette_leucoptere
cp audio/guifette_leucoptere/74852.mp3 src_audio/guifette_leucoptere
cp audio/guifette_leucoptere/74852.mp3.properties src_audio/guifette_leucoptere
cp audio/guifette_moustac/48768.mp3 src_audio/guifette_moustac
cp audio/guifette_moustac/48768.mp3.properties src_audio/guifette_moustac
cp audio/guifette_noire/104781.mp3 src_audio/guifette_noire
cp audio/guifette_noire/104781.mp3.properties src_audio/guifette_noire
cp audio/harelde_boreale/106033.mp3 src_audio/harelde_boreale
cp audio/harelde_boreale/106033.mp3.properties src_audio/harelde_boreale
cp audio/harelde_boreale/93196.mp3 src_audio/harelde_boreale
cp audio/harelde_boreale/93196.mp3.properties src_audio/harelde_boreale
cp audio/harle_huppe/107990.mp3 src_audio/harle_huppe
cp audio/harle_huppe/107990.mp3.properties src_audio/harle_huppe
cp audio/harle_huppe/26386.mp3 src_audio/harle_huppe
cp audio/harle_huppe/26386.mp3.properties src_audio/harle_huppe
cp audio/heron_cendre/37646.mp3 src_audio/heron_cendre
cp audio/heron_cendre/37646.mp3.properties src_audio/heron_cendre
cp audio/heron_cendre/71714.mp3 src_audio/heron_cendre
cp audio/heron_cendre/71714.mp3.properties src_audio/heron_cendre
cp audio/heron_garde-boeufs/108820.mp3 src_audio/heron_garde-boeufs
cp audio/heron_garde-boeufs/108820.mp3.properties src_audio/heron_garde-boeufs
cp audio/heron_garde-boeufs/53269.mp3 src_audio/heron_garde-boeufs
cp audio/heron_garde-boeufs/53269.mp3.properties src_audio/heron_garde-boeufs
cp audio/heron_pourpre/30134.mp3 src_audio/heron_pourpre
cp audio/heron_pourpre/30134.mp3.properties src_audio/heron_pourpre
cp audio/heron_pourpre/78507.mp3 src_audio/heron_pourpre
cp audio/heron_pourpre/78507.mp3.properties src_audio/heron_pourpre
cp audio/hibou_des_marais/27372.mp3 src_audio/hibou_des_marais
cp audio/hibou_des_marais/27372.mp3.properties src_audio/hibou_des_marais
cp audio/hibou_des_marais/56291.mp3 src_audio/hibou_des_marais
cp audio/hibou_des_marais/56291.mp3.properties src_audio/hibou_des_marais
cp audio/hibou_moyen-duc/42326.mp3 src_audio/hibou_moyen-duc
cp audio/hibou_moyen-duc/42326.mp3.properties src_audio/hibou_moyen-duc
cp audio/hirondelle_de_fenetre/106682.mp3 src_audio/hirondelle_de_fenetre
cp audio/hirondelle_de_fenetre/106682.mp3.properties src_audio/hirondelle_de_fenetre
cp audio/hirondelle_de_fenetre/44633.mp3 src_audio/hirondelle_de_fenetre
cp audio/hirondelle_de_fenetre/44633.mp3.properties src_audio/hirondelle_de_fenetre
cp audio/hirondelle_de_fenetre/44634.mp3 src_audio/hirondelle_de_fenetre
cp audio/hirondelle_de_fenetre/44634.mp3.properties src_audio/hirondelle_de_fenetre
cp audio/hirondelle_de_rivage/61815.mp3 src_audio/hirondelle_de_rivage
cp audio/hirondelle_de_rivage/61815.mp3.properties src_audio/hirondelle_de_rivage
cp audio/hirondelle_de_rochers/35842.mp3 src_audio/hirondelle_de_rochers
cp audio/hirondelle_de_rochers/35842.mp3.properties src_audio/hirondelle_de_rochers
cp audio/hirondelle_de_rochers/53735.mp3 src_audio/hirondelle_de_rochers
cp audio/hirondelle_de_rochers/53735.mp3.properties src_audio/hirondelle_de_rochers
cp audio/hirondelle_de_rochers/55175.mp3 src_audio/hirondelle_de_rochers
cp audio/hirondelle_de_rochers/55175.mp3.properties src_audio/hirondelle_de_rochers
cp audio/hirondelle_rousseline/94602.mp3 src_audio/hirondelle_rousseline
cp audio/hirondelle_rousseline/94602.mp3.properties src_audio/hirondelle_rousseline
cp audio/hirondelle_rustique/103853.mp3 src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/103853.mp3.properties src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/25649.mp3 src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/25649.mp3.properties src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/34293.mp3 src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/34293.mp3.properties src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/34544.mp3 src_audio/hirondelle_rustique
cp audio/hirondelle_rustique/34544.mp3.properties src_audio/hirondelle_rustique
cp audio/huitrier_pie/76241.mp3 src_audio/huitrier_pie
cp audio/huitrier_pie/76241.mp3.properties src_audio/huitrier_pie
cp audio/huitrier_pie/99913.mp3 src_audio/huitrier_pie
cp audio/huitrier_pie/99913.mp3.properties src_audio/huitrier_pie
cp audio/huppe_fasciee/24556.mp3 src_audio/huppe_fasciee
cp audio/huppe_fasciee/24556.mp3.properties src_audio/huppe_fasciee
cp audio/huppe_fasciee/94044.mp3 src_audio/huppe_fasciee
cp audio/huppe_fasciee/94044.mp3.properties src_audio/huppe_fasciee
cp audio/hypolais_icterine/26358.mp3 src_audio/hypolais_icterine
cp audio/hypolais_icterine/26358.mp3.properties src_audio/hypolais_icterine
cp audio/hypolais_polyglotte/29794.mp3 src_audio/hypolais_polyglotte
cp audio/hypolais_polyglotte/29794.mp3.properties src_audio/hypolais_polyglotte
cp audio/hypolais_polyglotte/55013.mp3 src_audio/hypolais_polyglotte
cp audio/hypolais_polyglotte/55013.mp3.properties src_audio/hypolais_polyglotte
cp audio/ibis_falcinelle/107009.mp3 src_audio/ibis_falcinelle
cp audio/ibis_falcinelle/107009.mp3.properties src_audio/ibis_falcinelle
cp audio/jaseur_boreal/115480.mp3 src_audio/jaseur_boreal
cp audio/jaseur_boreal/115480.mp3.properties src_audio/jaseur_boreal
cp audio/labbe_a_longue_queue/86801.mp3 src_audio/labbe_a_longue_queue
cp audio/labbe_a_longue_queue/86801.mp3.properties src_audio/labbe_a_longue_queue
cp audio/labbe_parasite/56944.mp3 src_audio/labbe_parasite
cp audio/labbe_parasite/56944.mp3.properties src_audio/labbe_parasite
cp audio/lagopede_alpin/109107.mp3 src_audio/lagopede_alpin
cp audio/lagopede_alpin/109107.mp3.properties src_audio/lagopede_alpin
cp audio/lagopede_des_saules/110507.mp3 src_audio/lagopede_des_saules
cp audio/lagopede_des_saules/110507.mp3.properties src_audio/lagopede_des_saules
cp audio/lagopede_des_saules/33463.mp3 src_audio/lagopede_des_saules
cp audio/lagopede_des_saules/33463.mp3.properties src_audio/lagopede_des_saules
cp audio/linotte_a_bec_jaune/100476.mp3 src_audio/linotte_a_bec_jaune
cp audio/linotte_a_bec_jaune/100476.mp3.properties src_audio/linotte_a_bec_jaune
cp audio/linotte_a_bec_jaune/121508.mp3 src_audio/linotte_a_bec_jaune
cp audio/linotte_a_bec_jaune/121508.mp3.properties src_audio/linotte_a_bec_jaune
cp audio/linotte_melodieuse/31720.mp3 src_audio/linotte_melodieuse
cp audio/linotte_melodieuse/31720.mp3.properties src_audio/linotte_melodieuse
cp audio/linotte_melodieuse/77390.mp3 src_audio/linotte_melodieuse
cp audio/linotte_melodieuse/77390.mp3.properties src_audio/linotte_melodieuse
cp audio/locustelle_luscinioide/26958.mp3 src_audio/locustelle_luscinioide
cp audio/locustelle_luscinioide/26958.mp3.properties src_audio/locustelle_luscinioide
cp audio/locustelle_luscinioide/42668.mp3 src_audio/locustelle_luscinioide
cp audio/locustelle_luscinioide/42668.mp3.properties src_audio/locustelle_luscinioide
cp audio/locustelle_tachetee/25656.mp3 src_audio/locustelle_tachetee
cp audio/locustelle_tachetee/25656.mp3.properties src_audio/locustelle_tachetee
cp audio/locustelle_tachetee/99954.mp3 src_audio/locustelle_tachetee
cp audio/locustelle_tachetee/99954.mp3.properties src_audio/locustelle_tachetee
cp audio/loriot_d_europe/27152.mp3 src_audio/loriot_d_europe
cp audio/loriot_d_europe/27152.mp3.properties src_audio/loriot_d_europe
cp audio/loriot_d_europe/90968.mp3 src_audio/loriot_d_europe
cp audio/loriot_d_europe/90968.mp3.properties src_audio/loriot_d_europe
cp audio/lusciniole_a_moustaches/115016.mp3 src_audio/lusciniole_a_moustaches
cp audio/lusciniole_a_moustaches/115016.mp3.properties src_audio/lusciniole_a_moustaches
cp audio/lusciniole_a_moustaches/31616.mp3 src_audio/lusciniole_a_moustaches
cp audio/lusciniole_a_moustaches/31616.mp3.properties src_audio/lusciniole_a_moustaches
cp audio/macreuse_noire/101006.mp3 src_audio/macreuse_noire
cp audio/macreuse_noire/101006.mp3.properties src_audio/macreuse_noire
cp audio/marouette_de_baillon/92001.mp3 src_audio/marouette_de_baillon
cp audio/marouette_de_baillon/92001.mp3.properties src_audio/marouette_de_baillon
cp audio/marouette_ponctuee/46742.mp3 src_audio/marouette_ponctuee
cp audio/marouette_ponctuee/46742.mp3.properties src_audio/marouette_ponctuee
cp audio/marouette_poussin/75186.mp3 src_audio/marouette_poussin
cp audio/marouette_poussin/75186.mp3.properties src_audio/marouette_poussin
cp audio/martinet_a_ventre_blanc/37405.mp3 src_audio/martinet_a_ventre_blanc
cp audio/martinet_a_ventre_blanc/37405.mp3.properties src_audio/martinet_a_ventre_blanc
cp audio/martinet_a_ventre_blanc/58617.mp3 src_audio/martinet_a_ventre_blanc
cp audio/martinet_a_ventre_blanc/58617.mp3.properties src_audio/martinet_a_ventre_blanc
cp audio/martinet_a_ventre_blanc/62846.mp3 src_audio/martinet_a_ventre_blanc
cp audio/martinet_a_ventre_blanc/62846.mp3.properties src_audio/martinet_a_ventre_blanc
cp audio/martinet_noir/118539.mp3 src_audio/martinet_noir
cp audio/martinet_noir/118539.mp3.properties src_audio/martinet_noir
cp audio/martinet_noir/30048.mp3 src_audio/martinet_noir
cp audio/martinet_noir/30048.mp3.properties src_audio/martinet_noir
cp audio/martinet_noir/37490.mp3 src_audio/martinet_noir
cp audio/martinet_noir/37490.mp3.properties src_audio/martinet_noir
cp audio/martinet_pale/30414.mp3 src_audio/martinet_pale
cp audio/martinet_pale/30414.mp3.properties src_audio/martinet_pale
cp audio/martinet_unicolore/80615.mp3 src_audio/martinet_unicolore
cp audio/martinet_unicolore/80615.mp3.properties src_audio/martinet_unicolore
cp audio/martin-pecheur_d_europe/106605.mp3 src_audio/martin-pecheur_d_europe
cp audio/martin-pecheur_d_europe/106605.mp3.properties src_audio/martin-pecheur_d_europe
cp audio/merle_a_plastron/55409.mp3 src_audio/merle_a_plastron
cp audio/merle_a_plastron/55409.mp3.properties src_audio/merle_a_plastron
cp audio/merle_a_plastron/98808.mp3 src_audio/merle_a_plastron
cp audio/merle_a_plastron/98808.mp3.properties src_audio/merle_a_plastron
cp audio/merle_a_plastron/Turdus_torquatus_calls_1983_04_22_A_27-5467-70115-135_Samsoe.mp3 src_audio/merle_a_plastron
cp audio/merle_a_plastron/Turdus_torquatus_calls_1983_04_22_A_27-5467-70115-135_Samsoe.mp3.properties src_audio/merle_a_plastron
cp audio/merle_noir/25745.mp3 src_audio/merle_noir
cp audio/merle_noir/25745.mp3.properties src_audio/merle_noir
cp audio/merle_noir/25870.mp3 src_audio/merle_noir
cp audio/merle_noir/25870.mp3.properties src_audio/merle_noir
cp audio/mesangeai_imitateur/57840.mp3 src_audio/mesangeai_imitateur
cp audio/mesangeai_imitateur/57840.mp3.properties src_audio/mesangeai_imitateur
cp audio/mesange_a_longue_queue/28192.mp3 src_audio/mesange_a_longue_queue
cp audio/mesange_a_longue_queue/28192.mp3.properties src_audio/mesange_a_longue_queue
cp audio/mesange_bleue/25737.mp3 src_audio/mesange_bleue
cp audio/mesange_bleue/25737.mp3.properties src_audio/mesange_bleue
cp audio/mesange_bleue/28210.mp3 src_audio/mesange_bleue
cp audio/mesange_bleue/28210.mp3.properties src_audio/mesange_bleue
cp audio/mesange_bleue/64616.mp3 src_audio/mesange_bleue
cp audio/mesange_bleue/64616.mp3.properties src_audio/mesange_bleue
cp audio/mesange_boreale/28199.mp3 src_audio/mesange_boreale
cp audio/mesange_boreale/28199.mp3.properties src_audio/mesange_boreale
cp audio/mesange_boreale/35078.mp3 src_audio/mesange_boreale
cp audio/mesange_boreale/35078.mp3.properties src_audio/mesange_boreale
cp audio/mesange_charbonniere/25667.mp3 src_audio/mesange_charbonniere
cp audio/mesange_charbonniere/25667.mp3.properties src_audio/mesange_charbonniere
cp audio/mesange_charbonniere/28214.mp3 src_audio/mesange_charbonniere
cp audio/mesange_charbonniere/28214.mp3.properties src_audio/mesange_charbonniere
cp audio/mesange_charbonniere/56233.mp3 src_audio/mesange_charbonniere
cp audio/mesange_charbonniere/56233.mp3.properties src_audio/mesange_charbonniere
cp audio/mesange_huppee/108433.mp3 src_audio/mesange_huppee
cp audio/mesange_huppee/108433.mp3.properties src_audio/mesange_huppee
cp audio/mesange_huppee/28202.mp3 src_audio/mesange_huppee
cp audio/mesange_huppee/28202.mp3.properties src_audio/mesange_huppee
cp audio/mesange_huppee/35038.mp3 src_audio/mesange_huppee
cp audio/mesange_huppee/35038.mp3.properties src_audio/mesange_huppee
cp audio/mesange_lapone/64739.mp3 src_audio/mesange_lapone
cp audio/mesange_lapone/64739.mp3.properties src_audio/mesange_lapone
cp audio/mesange_lugubre/117020.mp3 src_audio/mesange_lugubre
cp audio/mesange_lugubre/117020.mp3.properties src_audio/mesange_lugubre
cp audio/mesange_noire/19860.mp3 src_audio/mesange_noire
cp audio/mesange_noire/19860.mp3.properties src_audio/mesange_noire
cp audio/mesange_noire/28206.mp3 src_audio/mesange_noire
cp audio/mesange_noire/28206.mp3.properties src_audio/mesange_noire
cp audio/mesange_nonnette/25722.mp3 src_audio/mesange_nonnette
cp audio/mesange_nonnette/25722.mp3.properties src_audio/mesange_nonnette
cp audio/mesange_nonnette/28198.mp3 src_audio/mesange_nonnette
cp audio/mesange_nonnette/28198.mp3.properties src_audio/mesange_nonnette
cp audio/milan_royal/89115.mp3 src_audio/milan_royal
cp audio/milan_royal/89115.mp3.properties src_audio/milan_royal
cp audio/moineau_domestique/35174.mp3 src_audio/moineau_domestique
cp audio/moineau_domestique/35174.mp3.properties src_audio/moineau_domestique
cp audio/moineau_domestique/5954.mp3 src_audio/moineau_domestique
cp audio/moineau_domestique/5954.mp3.properties src_audio/moineau_domestique
cp audio/moineau_espagnol/120337.mp3 src_audio/moineau_espagnol
cp audio/moineau_espagnol/120337.mp3.properties src_audio/moineau_espagnol
cp audio/moineau_espagnol/30181.mp3 src_audio/moineau_espagnol
cp audio/moineau_espagnol/30181.mp3.properties src_audio/moineau_espagnol
cp audio/moineau_friquet/112853.mp3 src_audio/moineau_friquet
cp audio/moineau_friquet/112853.mp3.properties src_audio/moineau_friquet
cp audio/moineau_friquet/29162.mp3 src_audio/moineau_friquet
cp audio/moineau_friquet/29162.mp3.properties src_audio/moineau_friquet
cp audio/moineau_friquet/31868.mp3 src_audio/moineau_friquet
cp audio/moineau_friquet/31868.mp3.properties src_audio/moineau_friquet
cp audio/moineau_soulcie/28009.mp3 src_audio/moineau_soulcie
cp audio/moineau_soulcie/28009.mp3.properties src_audio/moineau_soulcie
cp audio/monticole_bleu/106975.mp3 src_audio/monticole_bleu
cp audio/monticole_bleu/106975.mp3.properties src_audio/monticole_bleu
cp audio/monticole_bleu/29453.mp3 src_audio/monticole_bleu
cp audio/monticole_bleu/29453.mp3.properties src_audio/monticole_bleu
cp audio/mouette_melanocephale/69861.mp3 src_audio/mouette_melanocephale
cp audio/mouette_melanocephale/69861.mp3.properties src_audio/mouette_melanocephale
cp audio/mouette_rieuse/44772.mp3 src_audio/mouette_rieuse
cp audio/mouette_rieuse/44772.mp3.properties src_audio/mouette_rieuse
cp audio/mouette_rieuse/83173.mp3 src_audio/mouette_rieuse
cp audio/mouette_rieuse/83173.mp3.properties src_audio/mouette_rieuse
cp audio/mouette_tridactyle/103016.mp3 src_audio/mouette_tridactyle
cp audio/mouette_tridactyle/103016.mp3.properties src_audio/mouette_tridactyle
cp audio/mouette_tridactyle/28372.mp3 src_audio/mouette_tridactyle
cp audio/mouette_tridactyle/28372.mp3.properties src_audio/mouette_tridactyle
cp audio/mouette_tridactyle/83969.mp3 src_audio/mouette_tridactyle
cp audio/mouette_tridactyle/83969.mp3.properties src_audio/mouette_tridactyle
cp audio/nette_rousse/96321.mp3 src_audio/nette_rousse
cp audio/nette_rousse/96321.mp3.properties src_audio/nette_rousse
cp audio/oceanite_tempete/46065.mp3 src_audio/oceanite_tempete
cp audio/oceanite_tempete/46065.mp3.properties src_audio/oceanite_tempete
cp audio/oedicneme_criard/29180.mp3 src_audio/oedicneme_criard
cp audio/oedicneme_criard/29180.mp3.properties src_audio/oedicneme_criard
cp audio/oie_a_bec_court/111863.mp3 src_audio/oie_a_bec_court
cp audio/oie_a_bec_court/111863.mp3.properties src_audio/oie_a_bec_court
cp audio/oie_a_bec_court/65142.mp3 src_audio/oie_a_bec_court
cp audio/oie_a_bec_court/65142.mp3.properties src_audio/oie_a_bec_court
cp audio/oie_cendree/42015.mp3 src_audio/oie_cendree
cp audio/oie_cendree/42015.mp3.properties src_audio/oie_cendree
cp audio/oie_cendree/71070.mp3 src_audio/oie_cendree
cp audio/oie_cendree/71070.mp3.properties src_audio/oie_cendree
cp audio/oie_cendree/83249.mp3 src_audio/oie_cendree
cp audio/oie_cendree/83249.mp3.properties src_audio/oie_cendree
cp audio/oie_des_moissons/109681.mp3 src_audio/oie_des_moissons
cp audio/oie_des_moissons/109681.mp3.properties src_audio/oie_des_moissons
cp audio/oie_des_moissons/48195.mp3 src_audio/oie_des_moissons
cp audio/oie_des_moissons/48195.mp3.properties src_audio/oie_des_moissons
cp audio/oie_naine/110805.mp3 src_audio/oie_naine
cp audio/oie_naine/110805.mp3.properties src_audio/oie_naine
cp audio/oie_rieuse/113143.mp3 src_audio/oie_rieuse
cp audio/oie_rieuse/113143.mp3.properties src_audio/oie_rieuse
cp audio/ouette_d_egypte/58659.mp3 src_audio/ouette_d_egypte
cp audio/ouette_d_egypte/58659.mp3.properties src_audio/ouette_d_egypte
cp audio/ouette_d_egypte/94721.mp3 src_audio/ouette_d_egypte
cp audio/ouette_d_egypte/94721.mp3.properties src_audio/ouette_d_egypte
cp audio/panure_a_moustaches/22687.mp3 src_audio/panure_a_moustaches
cp audio/panure_a_moustaches/22687.mp3.properties src_audio/panure_a_moustaches
cp audio/perdrix_choukar/72875.mp3 src_audio/perdrix_choukar
cp audio/perdrix_choukar/72875.mp3.properties src_audio/perdrix_choukar
cp audio/perdrix_grise/42430.mp3 src_audio/perdrix_grise
cp audio/perdrix_grise/42430.mp3.properties src_audio/perdrix_grise
cp audio/perdrix_grise/96929.mp3 src_audio/perdrix_grise
cp audio/perdrix_grise/96929.mp3.properties src_audio/perdrix_grise
cp audio/perdrix_rouge/61796.mp3 src_audio/perdrix_rouge
cp audio/perdrix_rouge/61796.mp3.properties src_audio/perdrix_rouge
cp audio/petit-duc_scops/29068.mp3 src_audio/petit-duc_scops
cp audio/petit-duc_scops/29068.mp3.properties src_audio/petit-duc_scops
cp audio/petit-duc_scops/29197.mp3 src_audio/petit-duc_scops
cp audio/petit-duc_scops/29197.mp3.properties src_audio/petit-duc_scops
cp audio/petit_gravelot/27974.mp3 src_audio/petit_gravelot
cp audio/petit_gravelot/27974.mp3.properties src_audio/petit_gravelot
cp audio/phalarope_a_bec_etroit/111586.mp3 src_audio/phalarope_a_bec_etroit
cp audio/phalarope_a_bec_etroit/111586.mp3.properties src_audio/phalarope_a_bec_etroit
cp audio/phalarope_a_bec_etroit/46110.mp3 src_audio/phalarope_a_bec_etroit
cp audio/phalarope_a_bec_etroit/46110.mp3.properties src_audio/phalarope_a_bec_etroit
cp audio/phalarope_a_bec_etroit/64758.mp3 src_audio/phalarope_a_bec_etroit
cp audio/phalarope_a_bec_etroit/64758.mp3.properties src_audio/phalarope_a_bec_etroit
cp audio/phalarope_a_bec_large/107606.mp3 src_audio/phalarope_a_bec_large
cp audio/phalarope_a_bec_large/107606.mp3.properties src_audio/phalarope_a_bec_large
cp audio/phalarope_a_bec_large/40499.mp3 src_audio/phalarope_a_bec_large
cp audio/phalarope_a_bec_large/40499.mp3.properties src_audio/phalarope_a_bec_large
cp audio/phalarope_a_bec_large/53462.mp3 src_audio/phalarope_a_bec_large
cp audio/phalarope_a_bec_large/53462.mp3.properties src_audio/phalarope_a_bec_large
cp audio/phragmite_aquatique/99397.mp3 src_audio/phragmite_aquatique
cp audio/phragmite_aquatique/99397.mp3.properties src_audio/phragmite_aquatique
cp audio/phragmite_des_joncs/24929.mp3 src_audio/phragmite_des_joncs
cp audio/phragmite_des_joncs/24929.mp3.properties src_audio/phragmite_des_joncs
cp audio/phragmite_des_joncs/24935.mp3 src_audio/phragmite_des_joncs
cp audio/phragmite_des_joncs/24935.mp3.properties src_audio/phragmite_des_joncs
cp audio/pic_a_dos_blanc/37762.mp3 src_audio/pic_a_dos_blanc
cp audio/pic_a_dos_blanc/37762.mp3.properties src_audio/pic_a_dos_blanc
cp audio/pic_a_dos_blanc/83977.mp3 src_audio/pic_a_dos_blanc
cp audio/pic_a_dos_blanc/83977.mp3.properties src_audio/pic_a_dos_blanc
cp audio/pic_cendre/20028.mp3 src_audio/pic_cendre
cp audio/pic_cendre/20028.mp3.properties src_audio/pic_cendre
cp audio/pic_cendre/92347.mp3 src_audio/pic_cendre
cp audio/pic_cendre/92347.mp3.properties src_audio/pic_cendre
cp audio/pic_epeiche/27046.mp3 src_audio/pic_epeiche
cp audio/pic_epeiche/27046.mp3.properties src_audio/pic_epeiche
cp audio/pic_epeiche/37504.mp3 src_audio/pic_epeiche
cp audio/pic_epeiche/37504.mp3.properties src_audio/pic_epeiche
cp audio/pic_epeichette/42424.mp3 src_audio/pic_epeichette
cp audio/pic_epeichette/42424.mp3.properties src_audio/pic_epeichette
cp audio/pic_epeichette/96529.mp3 src_audio/pic_epeichette
cp audio/pic_epeichette/96529.mp3.properties src_audio/pic_epeichette
cp audio/pic_mar/26678.mp3 src_audio/pic_mar
cp audio/pic_mar/26678.mp3.properties src_audio/pic_mar
cp audio/pic_mar/31667.mp3 src_audio/pic_mar
cp audio/pic_mar/31667.mp3.properties src_audio/pic_mar
cp audio/pic_noir/29000.mp3 src_audio/pic_noir
cp audio/pic_noir/29000.mp3.properties src_audio/pic_noir
cp audio/pic_noir/31079.mp3 src_audio/pic_noir
cp audio/pic_noir/31079.mp3.properties src_audio/pic_noir
cp audio/pic_noir/42556.mp3 src_audio/pic_noir
cp audio/pic_noir/42556.mp3.properties src_audio/pic_noir
cp audio/pic_syriaque/71522.mp3 src_audio/pic_syriaque
cp audio/pic_syriaque/71522.mp3.properties src_audio/pic_syriaque
cp audio/pic_tridactyle/37761.mp3 src_audio/pic_tridactyle
cp audio/pic_tridactyle/37761.mp3.properties src_audio/pic_tridactyle
cp audio/pic_tridactyle/57842.mp3 src_audio/pic_tridactyle
cp audio/pic_tridactyle/57842.mp3.properties src_audio/pic_tridactyle
cp audio/pic_tridactyle/90956.mp3 src_audio/pic_tridactyle
cp audio/pic_tridactyle/90956.mp3.properties src_audio/pic_tridactyle
cp audio/pic_vert/103160.mp3 src_audio/pic_vert
cp audio/pic_vert/103160.mp3.properties src_audio/pic_vert
cp audio/pic_vert/35057.mp3 src_audio/pic_vert
cp audio/pic_vert/35057.mp3.properties src_audio/pic_vert
cp audio/pic_vert/41827.mp3 src_audio/pic_vert
cp audio/pic_vert/41827.mp3.properties src_audio/pic_vert
cp audio/pic_vert/84053.mp3 src_audio/pic_vert
cp audio/pic_vert/84053.mp3.properties src_audio/pic_vert
cp audio/pie_bavarde/27142.mp3 src_audio/pie_bavarde
cp audio/pie_bavarde/27142.mp3.properties src_audio/pie_bavarde
cp audio/pie_bavarde/42619.mp3 src_audio/pie_bavarde
cp audio/pie_bavarde/42619.mp3.properties src_audio/pie_bavarde
cp audio/pie_bleue/114543.mp3 src_audio/pie_bleue
cp audio/pie_bleue/114543.mp3.properties src_audio/pie_bleue
cp audio/pie-grieche_a_poitrine_rose/29224.mp3 src_audio/pie-grieche_a_poitrine_rose
cp audio/pie-grieche_a_poitrine_rose/29224.mp3.properties src_audio/pie-grieche_a_poitrine_rose
cp audio/pie-grieche_a_tete_rousse/29475.mp3 src_audio/pie-grieche_a_tete_rousse
cp audio/pie-grieche_a_tete_rousse/29475.mp3.properties src_audio/pie-grieche_a_tete_rousse
cp audio/pie-grieche_a_tete_rousse/61263.mp3 src_audio/pie-grieche_a_tete_rousse
cp audio/pie-grieche_a_tete_rousse/61263.mp3.properties src_audio/pie-grieche_a_tete_rousse
cp audio/pie-grieche_ecorcheur/33991.mp3 src_audio/pie-grieche_ecorcheur
cp audio/pie-grieche_ecorcheur/33991.mp3.properties src_audio/pie-grieche_ecorcheur
cp audio/pie-grieche_ecorcheur/35326.mp3 src_audio/pie-grieche_ecorcheur
cp audio/pie-grieche_ecorcheur/35326.mp3.properties src_audio/pie-grieche_ecorcheur
cp audio/pie-grieche_grise/44982.mp3 src_audio/pie-grieche_grise
cp audio/pie-grieche_grise/44982.mp3.properties src_audio/pie-grieche_grise
cp audio/pie-grieche_grise/91969.mp3 src_audio/pie-grieche_grise
cp audio/pie-grieche_grise/91969.mp3.properties src_audio/pie-grieche_grise
cp audio/pie-grieche_masquee/101671.mp3 src_audio/pie-grieche_masquee
cp audio/pie-grieche_masquee/101671.mp3.properties src_audio/pie-grieche_masquee
cp audio/pigeon_biset/48676.mp3 src_audio/pigeon_biset
cp audio/pigeon_biset/48676.mp3.properties src_audio/pigeon_biset
cp audio/pigeon_biset/56697.mp3 src_audio/pigeon_biset
cp audio/pigeon_biset/56697.mp3.properties src_audio/pigeon_biset
cp audio/pigeon_colombin/53812.mp3 src_audio/pigeon_colombin
cp audio/pigeon_colombin/53812.mp3.properties src_audio/pigeon_colombin
cp audio/pigeon_ramier/35082.mp3 src_audio/pigeon_ramier
cp audio/pigeon_ramier/35082.mp3.properties src_audio/pigeon_ramier
cp audio/pigeon_ramier/91234.mp3 src_audio/pigeon_ramier
cp audio/pigeon_ramier/91234.mp3.properties src_audio/pigeon_ramier
cp audio/pinson_des_arbres/25643.mp3 src_audio/pinson_des_arbres
cp audio/pinson_des_arbres/25643.mp3.properties src_audio/pinson_des_arbres
cp audio/pinson_des_arbres/71688.mp3 src_audio/pinson_des_arbres
cp audio/pinson_des_arbres/71688.mp3.properties src_audio/pinson_des_arbres
cp audio/pinson_du_nord/25170.mp3 src_audio/pinson_du_nord
cp audio/pinson_du_nord/25170.mp3.properties src_audio/pinson_du_nord
cp audio/pinson_du_nord/62833.mp3 src_audio/pinson_du_nord
cp audio/pinson_du_nord/62833.mp3.properties src_audio/pinson_du_nord
cp audio/pinson_du_nord/64612.mp3 src_audio/pinson_du_nord
cp audio/pinson_du_nord/64612.mp3.properties src_audio/pinson_du_nord
cp audio/pipit_a_gorge_rousse/23904.mp3 src_audio/pipit_a_gorge_rousse
cp audio/pipit_a_gorge_rousse/23904.mp3.properties src_audio/pipit_a_gorge_rousse
cp audio/pipit_a_gorge_rousse/27009.mp3 src_audio/pipit_a_gorge_rousse
cp audio/pipit_a_gorge_rousse/27009.mp3.properties src_audio/pipit_a_gorge_rousse
cp audio/pipit_des_arbres/25613.mp3 src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/25613.mp3.properties src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/27013.mp3 src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/27013.mp3.properties src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/35403.mp3 src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/35403.mp3.properties src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/89698.mp3 src_audio/pipit_des_arbres
cp audio/pipit_des_arbres/89698.mp3.properties src_audio/pipit_des_arbres
cp audio/pipit_farlouse/101097.mp3 src_audio/pipit_farlouse
cp audio/pipit_farlouse/101097.mp3.properties src_audio/pipit_farlouse
cp audio/pipit_farlouse/30614.mp3 src_audio/pipit_farlouse
cp audio/pipit_farlouse/30614.mp3.properties src_audio/pipit_farlouse
cp audio/pipit_farlouse/67331.mp3 src_audio/pipit_farlouse
cp audio/pipit_farlouse/67331.mp3.properties src_audio/pipit_farlouse
cp audio/pipit_maritime/110353.mp3 src_audio/pipit_maritime
cp audio/pipit_maritime/110353.mp3.properties src_audio/pipit_maritime
cp audio/pipit_rousseline/118120.mp3 src_audio/pipit_rousseline
cp audio/pipit_rousseline/118120.mp3.properties src_audio/pipit_rousseline
cp audio/pipit_rousseline/22720.mp3 src_audio/pipit_rousseline
cp audio/pipit_rousseline/22720.mp3.properties src_audio/pipit_rousseline
cp audio/pipit_rousseline/98667.mp3 src_audio/pipit_rousseline
cp audio/pipit_rousseline/98667.mp3.properties src_audio/pipit_rousseline
cp audio/pipit_spioncelle/26778.mp3 src_audio/pipit_spioncelle
cp audio/pipit_spioncelle/26778.mp3.properties src_audio/pipit_spioncelle
cp audio/pipit_spioncelle/73130.mp3 src_audio/pipit_spioncelle
cp audio/pipit_spioncelle/73130.mp3.properties src_audio/pipit_spioncelle
cp audio/plongeon_arctique/34107.mp3 src_audio/plongeon_arctique
cp audio/plongeon_arctique/34107.mp3.properties src_audio/plongeon_arctique
cp audio/plongeon_arctique/67279.mp3 src_audio/plongeon_arctique
cp audio/plongeon_arctique/67279.mp3.properties src_audio/plongeon_arctique
cp audio/plongeon_catmarin/58569.mp3 src_audio/plongeon_catmarin
cp audio/plongeon_catmarin/58569.mp3.properties src_audio/plongeon_catmarin
cp audio/plongeon_catmarin/58577.mp3 src_audio/plongeon_catmarin
cp audio/plongeon_catmarin/58577.mp3.properties src_audio/plongeon_catmarin
cp audio/plongeon_catmarin/58582.mp3 src_audio/plongeon_catmarin
cp audio/plongeon_catmarin/58582.mp3.properties src_audio/plongeon_catmarin
cp audio/plongeon_imbrin/1371.mp3 src_audio/plongeon_imbrin
cp audio/plongeon_imbrin/1371.mp3.properties src_audio/plongeon_imbrin
cp audio/pluvier_argente/25685.mp3 src_audio/pluvier_argente
cp audio/pluvier_argente/25685.mp3.properties src_audio/pluvier_argente
cp audio/pluvier_argente/48578.mp3 src_audio/pluvier_argente
cp audio/pluvier_argente/48578.mp3.properties src_audio/pluvier_argente
cp audio/pluvier_dore/42344.mp3 src_audio/pluvier_dore
cp audio/pluvier_dore/42344.mp3.properties src_audio/pluvier_dore
cp audio/pluvier_dore/57535.mp3 src_audio/pluvier_dore
cp audio/pluvier_dore/57535.mp3.properties src_audio/pluvier_dore
cp audio/pluvier_guignard/25159.mp3 src_audio/pluvier_guignard
cp audio/pluvier_guignard/25159.mp3.properties src_audio/pluvier_guignard
cp audio/pluvier_guignard/62795.mp3 src_audio/pluvier_guignard
cp audio/pluvier_guignard/62795.mp3.properties src_audio/pluvier_guignard
cp audio/pouillot_a_grands_sourcils/26011.mp3 src_audio/pouillot_a_grands_sourcils
cp audio/pouillot_a_grands_sourcils/26011.mp3.properties src_audio/pouillot_a_grands_sourcils
cp audio/pouillot_a_grands_sourcils/36356.mp3 src_audio/pouillot_a_grands_sourcils
cp audio/pouillot_a_grands_sourcils/36356.mp3.properties src_audio/pouillot_a_grands_sourcils
cp audio/pouillot_boreal/26777.mp3 src_audio/pouillot_boreal
cp audio/pouillot_boreal/26777.mp3.properties src_audio/pouillot_boreal
cp audio/pouillot_boreal/26866.mp3 src_audio/pouillot_boreal
cp audio/pouillot_boreal/26866.mp3.properties src_audio/pouillot_boreal
cp audio/pouillot_brun/27251.mp3 src_audio/pouillot_brun
cp audio/pouillot_brun/27251.mp3.properties src_audio/pouillot_brun
cp audio/pouillot_de_bonelli/29778.mp3 src_audio/pouillot_de_bonelli
cp audio/pouillot_de_bonelli/29778.mp3.properties src_audio/pouillot_de_bonelli
cp audio/pouillot_de_bonelli/76887.mp3 src_audio/pouillot_de_bonelli
cp audio/pouillot_de_bonelli/76887.mp3.properties src_audio/pouillot_de_bonelli
cp audio/pouillot_des_canaries/90793.mp3 src_audio/pouillot_des_canaries
cp audio/pouillot_des_canaries/90793.mp3.properties src_audio/pouillot_des_canaries
cp audio/pouillot_des_canaries/90794.mp3 src_audio/pouillot_des_canaries
cp audio/pouillot_des_canaries/90794.mp3.properties src_audio/pouillot_des_canaries
cp audio/pouillot_fitis/25116.mp3 src_audio/pouillot_fitis
cp audio/pouillot_fitis/25116.mp3.properties src_audio/pouillot_fitis
cp audio/pouillot_fitis/25139.mp3 src_audio/pouillot_fitis
cp audio/pouillot_fitis/25139.mp3.properties src_audio/pouillot_fitis
cp audio/pouillot_fitis/26760.mp3 src_audio/pouillot_fitis
cp audio/pouillot_fitis/26760.mp3.properties src_audio/pouillot_fitis
cp audio/pouillot_iberique/26671.mp3 src_audio/pouillot_iberique
cp audio/pouillot_iberique/26671.mp3.properties src_audio/pouillot_iberique
cp audio/pouillot_iberique/62721.mp3 src_audio/pouillot_iberique
cp audio/pouillot_iberique/62721.mp3.properties src_audio/pouillot_iberique
cp audio/pouillot_siffleur/29760.mp3 src_audio/pouillot_siffleur
cp audio/pouillot_siffleur/29760.mp3.properties src_audio/pouillot_siffleur
cp audio/pouillot_siffleur/56005.mp3 src_audio/pouillot_siffleur
cp audio/pouillot_siffleur/56005.mp3.properties src_audio/pouillot_siffleur
cp audio/pouillot_veloce/19853.mp3 src_audio/pouillot_veloce
cp audio/pouillot_veloce/19853.mp3.properties src_audio/pouillot_veloce
cp audio/pouillot_veloce/39436.mp3 src_audio/pouillot_veloce
cp audio/pouillot_veloce/39436.mp3.properties src_audio/pouillot_veloce
cp audio/pouillot_verdatre/19942.mp3 src_audio/pouillot_verdatre
cp audio/pouillot_verdatre/19942.mp3.properties src_audio/pouillot_verdatre
cp audio/puffin_cendre/103146.mp3 src_audio/puffin_cendre
cp audio/puffin_cendre/103146.mp3.properties src_audio/puffin_cendre
cp audio/pygargue_a_queue_blanche/36340.mp3 src_audio/pygargue_a_queue_blanche
cp audio/pygargue_a_queue_blanche/36340.mp3.properties src_audio/pygargue_a_queue_blanche
cp audio/pygargue_a_queue_blanche/98156.mp3 src_audio/pygargue_a_queue_blanche
cp audio/pygargue_a_queue_blanche/98156.mp3.properties src_audio/pygargue_a_queue_blanche
cp audio/rale_d_eau/25688.mp3 src_audio/rale_d_eau
cp audio/rale_d_eau/25688.mp3.properties src_audio/rale_d_eau
cp audio/rale_d_eau/42670.mp3 src_audio/rale_d_eau
cp audio/rale_d_eau/42670.mp3.properties src_audio/rale_d_eau
cp audio/rale_des_genets/26924.mp3 src_audio/rale_des_genets
cp audio/rale_des_genets/26924.mp3.properties src_audio/rale_des_genets
cp audio/rale_des_genets/91556.mp3 src_audio/rale_des_genets
cp audio/rale_des_genets/91556.mp3.properties src_audio/rale_des_genets
cp audio/remiz_penduline/25919.mp3 src_audio/remiz_penduline
cp audio/remiz_penduline/25919.mp3.properties src_audio/remiz_penduline
cp audio/remiz_penduline/35980.mp3 src_audio/remiz_penduline
cp audio/remiz_penduline/35980.mp3.properties src_audio/remiz_penduline
cp audio/roitelet_a_triple_bandeau/28232.mp3 src_audio/roitelet_a_triple_bandeau
cp audio/roitelet_a_triple_bandeau/28232.mp3.properties src_audio/roitelet_a_triple_bandeau
cp audio/roitelet_a_triple_bandeau/39295.mp3 src_audio/roitelet_a_triple_bandeau
cp audio/roitelet_a_triple_bandeau/39295.mp3.properties src_audio/roitelet_a_triple_bandeau
cp audio/roitelet_huppe/112608.mp3 src_audio/roitelet_huppe
cp audio/roitelet_huppe/112608.mp3.properties src_audio/roitelet_huppe
cp audio/roitelet_huppe/23366.mp3 src_audio/roitelet_huppe
cp audio/roitelet_huppe/23366.mp3.properties src_audio/roitelet_huppe
cp audio/roitelet_huppe/30237.mp3 src_audio/roitelet_huppe
cp audio/roitelet_huppe/30237.mp3.properties src_audio/roitelet_huppe
cp audio/rollier_d_europe/49441.mp3 src_audio/rollier_d_europe
cp audio/rollier_d_europe/49441.mp3.properties src_audio/rollier_d_europe
cp audio/rollier_d_europe/97040.mp3 src_audio/rollier_d_europe
cp audio/rollier_d_europe/97040.mp3.properties src_audio/rollier_d_europe
cp audio/roselin_cramoisi/25065.mp3 src_audio/roselin_cramoisi
cp audio/roselin_cramoisi/25065.mp3.properties src_audio/roselin_cramoisi
cp audio/roselin_cramoisi/67246.mp3 src_audio/roselin_cramoisi
cp audio/roselin_cramoisi/67246.mp3.properties src_audio/roselin_cramoisi
cp audio/rossignol_philomele/19660.mp3 src_audio/rossignol_philomele
cp audio/rossignol_philomele/19660.mp3.properties src_audio/rossignol_philomele
cp audio/rossignol_philomele/35409.mp3 src_audio/rossignol_philomele
cp audio/rossignol_philomele/35409.mp3.properties src_audio/rossignol_philomele
cp audio/rossignol_philomele/36983.mp3 src_audio/rossignol_philomele
cp audio/rossignol_philomele/36983.mp3.properties src_audio/rossignol_philomele
cp audio/rossignol_progne/103769.mp3 src_audio/rossignol_progne
cp audio/rossignol_progne/103769.mp3.properties src_audio/rossignol_progne
cp audio/rossignol_progne/25663.mp3 src_audio/rossignol_progne
cp audio/rossignol_progne/25663.mp3.properties src_audio/rossignol_progne
cp audio/rossignol_progne/41336.mp3 src_audio/rossignol_progne
cp audio/rossignol_progne/41336.mp3.properties src_audio/rossignol_progne
cp audio/rougegorge_familier/25638.mp3 src_audio/rougegorge_familier
cp audio/rougegorge_familier/25638.mp3.properties src_audio/rougegorge_familier
cp audio/rougegorge_familier/27560.mp3 src_audio/rougegorge_familier
cp audio/rougegorge_familier/27560.mp3.properties src_audio/rougegorge_familier
cp audio/rougegorge_familier/80317.mp3 src_audio/rougegorge_familier
cp audio/rougegorge_familier/80317.mp3.properties src_audio/rougegorge_familier
cp audio/rougequeue_a_front_blanc/25742.mp3 src_audio/rougequeue_a_front_blanc
cp audio/rougequeue_a_front_blanc/25742.mp3.properties src_audio/rougequeue_a_front_blanc
cp audio/rougequeue_a_front_blanc/85972.mp3 src_audio/rougequeue_a_front_blanc
cp audio/rougequeue_a_front_blanc/85972.mp3.properties src_audio/rougequeue_a_front_blanc
cp audio/rougequeue_a_front_blanc/90974.mp3 src_audio/rougequeue_a_front_blanc
cp audio/rougequeue_a_front_blanc/90974.mp3.properties src_audio/rougequeue_a_front_blanc
cp audio/rougequeue_noir/75594.mp3 src_audio/rougequeue_noir
cp audio/rougequeue_noir/75594.mp3.properties src_audio/rougequeue_noir
cp audio/rousserolle_des_buissons/19604.mp3 src_audio/rousserolle_des_buissons
cp audio/rousserolle_des_buissons/19604.mp3.properties src_audio/rousserolle_des_buissons
cp audio/rousserolle_des_buissons/98673.mp3 src_audio/rousserolle_des_buissons
cp audio/rousserolle_des_buissons/98673.mp3.properties src_audio/rousserolle_des_buissons
cp audio/rousserolle_effarvatte/19625.mp3 src_audio/rousserolle_effarvatte
cp audio/rousserolle_effarvatte/19625.mp3.properties src_audio/rousserolle_effarvatte
cp audio/rousserolle_effarvatte/27123.mp3 src_audio/rousserolle_effarvatte
cp audio/rousserolle_effarvatte/27123.mp3.properties src_audio/rousserolle_effarvatte
cp audio/rousserolle_turdoide/18967.mp3 src_audio/rousserolle_turdoide
cp audio/rousserolle_turdoide/18967.mp3.properties src_audio/rousserolle_turdoide
cp audio/rousserolle_turdoide/42449.mp3 src_audio/rousserolle_turdoide
cp audio/rousserolle_turdoide/42449.mp3.properties src_audio/rousserolle_turdoide
cp audio/rousserolle_verderolle/24714.mp3 src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/24714.mp3.properties src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/54622.mp3 src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/54622.mp3.properties src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/94471.mp3 src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/94471.mp3.properties src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/Acrocephalus_palustris_55.70_12.30_10_m_Porsemosen_Denmark_5_Jun_2010_0600_hrs_NKrabbe_song.mp3 src_audio/rousserolle_verderolle
cp audio/rousserolle_verderolle/Acrocephalus_palustris_55.70_12.30_10_m_Porsemosen_Denmark_5_Jun_2010_0600_hrs_NKrabbe_song.mp3.properties src_audio/rousserolle_verderolle
cp audio/sarcelle_d_ete/26962.mp3 src_audio/sarcelle_d_ete
cp audio/sarcelle_d_ete/26962.mp3.properties src_audio/sarcelle_d_ete
cp audio/sarcelle_d_hiver/42338.mp3 src_audio/sarcelle_d_hiver
cp audio/sarcelle_d_hiver/42338.mp3.properties src_audio/sarcelle_d_hiver
cp audio/sarcelle_d_hiver/64736.mp3 src_audio/sarcelle_d_hiver
cp audio/sarcelle_d_hiver/64736.mp3.properties src_audio/sarcelle_d_hiver
cp audio/sarcelle_d_hiver/76788.mp3 src_audio/sarcelle_d_hiver
cp audio/sarcelle_d_hiver/76788.mp3.properties src_audio/sarcelle_d_hiver
cp audio/serin_cini/112193.mp3 src_audio/serin_cini
cp audio/serin_cini/112193.mp3.properties src_audio/serin_cini
cp audio/serin_cini/29473.mp3 src_audio/serin_cini
cp audio/serin_cini/29473.mp3.properties src_audio/serin_cini
cp audio/serin_cini/74373.mp3 src_audio/serin_cini
cp audio/serin_cini/74373.mp3.properties src_audio/serin_cini
cp audio/serin_des_canaries/79800.mp3 src_audio/serin_des_canaries
cp audio/serin_des_canaries/79800.mp3.properties src_audio/serin_des_canaries
cp audio/sittelle_torchepot/23419.mp3 src_audio/sittelle_torchepot
cp audio/sittelle_torchepot/23419.mp3.properties src_audio/sittelle_torchepot
cp audio/sittelle_torchepot/25763.mp3 src_audio/sittelle_torchepot
cp audio/sittelle_torchepot/25763.mp3.properties src_audio/sittelle_torchepot
cp audio/sizerin_blanchatre/64631.mp3 src_audio/sizerin_blanchatre
cp audio/sizerin_blanchatre/64631.mp3.properties src_audio/sizerin_blanchatre
cp audio/sizerin_blanchatre/65804.mp3 src_audio/sizerin_blanchatre
cp audio/sizerin_blanchatre/65804.mp3.properties src_audio/sizerin_blanchatre
cp audio/sizerin_blanchatre/93009.mp3 src_audio/sizerin_blanchatre
cp audio/sizerin_blanchatre/93009.mp3.properties src_audio/sizerin_blanchatre
cp audio/sizerin_flamme/41075.mp3 src_audio/sizerin_flamme
cp audio/sizerin_flamme/41075.mp3.properties src_audio/sizerin_flamme
cp audio/sizerin_flamme/55413.mp3 src_audio/sizerin_flamme
cp audio/sizerin_flamme/55413.mp3.properties src_audio/sizerin_flamme
cp audio/sterne_arctique/5767.mp3 src_audio/sterne_arctique
cp audio/sterne_arctique/5767.mp3.properties src_audio/sterne_arctique
cp audio/sterne_caspienne/108421.mp3 src_audio/sterne_caspienne
cp audio/sterne_caspienne/108421.mp3.properties src_audio/sterne_caspienne
cp audio/sterne_caugek/37592.mp3 src_audio/sterne_caugek
cp audio/sterne_caugek/37592.mp3.properties src_audio/sterne_caugek
cp audio/sterne_caugek/67429.mp3 src_audio/sterne_caugek
cp audio/sterne_caugek/67429.mp3.properties src_audio/sterne_caugek
cp audio/sterne_de_dougall/59500.mp3 src_audio/sterne_de_dougall
cp audio/sterne_de_dougall/59500.mp3.properties src_audio/sterne_de_dougall
cp audio/sterne_hansel/35181.mp3 src_audio/sterne_hansel
cp audio/sterne_hansel/35181.mp3.properties src_audio/sterne_hansel
cp audio/sterne_hansel/66121.mp3 src_audio/sterne_hansel
cp audio/sterne_hansel/66121.mp3.properties src_audio/sterne_hansel
cp audio/sterne_naine/35194.mp3 src_audio/sterne_naine
cp audio/sterne_naine/35194.mp3.properties src_audio/sterne_naine
cp audio/sterne_naine/37507.mp3 src_audio/sterne_naine
cp audio/sterne_naine/37507.mp3.properties src_audio/sterne_naine
cp audio/sterne_pierregarin/37492.mp3 src_audio/sterne_pierregarin
cp audio/sterne_pierregarin/37492.mp3.properties src_audio/sterne_pierregarin
cp audio/tadorne_casarca/74646.mp3 src_audio/tadorne_casarca
cp audio/tadorne_casarca/74646.mp3.properties src_audio/tadorne_casarca
cp audio/tadorne_de_belon/25701.mp3 src_audio/tadorne_de_belon
cp audio/tadorne_de_belon/25701.mp3.properties src_audio/tadorne_de_belon
cp audio/tadorne_de_belon/42275.mp3 src_audio/tadorne_de_belon
cp audio/tadorne_de_belon/42275.mp3.properties src_audio/tadorne_de_belon
cp audio/tadorne_de_belon/67100.mp3 src_audio/tadorne_de_belon
cp audio/tadorne_de_belon/67100.mp3.properties src_audio/tadorne_de_belon
cp audio/tarier_des_pres/27571.mp3 src_audio/tarier_des_pres
cp audio/tarier_des_pres/27571.mp3.properties src_audio/tarier_des_pres
cp audio/tarier_des_pres/29235.mp3 src_audio/tarier_des_pres
cp audio/tarier_des_pres/29235.mp3.properties src_audio/tarier_des_pres
cp audio/tarier_des_pres/36484.mp3 src_audio/tarier_des_pres
cp audio/tarier_des_pres/36484.mp3.properties src_audio/tarier_des_pres
cp audio/tarier_patre/78950.mp3 src_audio/tarier_patre
cp audio/tarier_patre/78950.mp3.properties src_audio/tarier_patre
cp audio/tarier_patre/99618.mp3 src_audio/tarier_patre
cp audio/tarier_patre/99618.mp3.properties src_audio/tarier_patre
cp audio/tarin_des_aulnes/27604.mp3 src_audio/tarin_des_aulnes
cp audio/tarin_des_aulnes/27604.mp3.properties src_audio/tarin_des_aulnes
cp audio/tarin_des_aulnes/35044.mp3 src_audio/tarin_des_aulnes
cp audio/tarin_des_aulnes/35044.mp3.properties src_audio/tarin_des_aulnes
cp audio/tetras_lyre/42428.mp3 src_audio/tetras_lyre
cp audio/tetras_lyre/42428.mp3.properties src_audio/tetras_lyre
cp audio/torcol_fourmilier/19666.mp3 src_audio/torcol_fourmilier
cp audio/torcol_fourmilier/19666.mp3.properties src_audio/torcol_fourmilier
cp audio/torcol_fourmilier/75468.mp3 src_audio/torcol_fourmilier
cp audio/torcol_fourmilier/75468.mp3.properties src_audio/torcol_fourmilier
cp audio/tournepierre_a_collier/106035.mp3 src_audio/tournepierre_a_collier
cp audio/tournepierre_a_collier/106035.mp3.properties src_audio/tournepierre_a_collier
cp audio/tournepierre_a_collier/90294.mp3 src_audio/tournepierre_a_collier
cp audio/tournepierre_a_collier/90294.mp3.properties src_audio/tournepierre_a_collier
cp audio/tournepierre_a_collier/93409.mp3 src_audio/tournepierre_a_collier
cp audio/tournepierre_a_collier/93409.mp3.properties src_audio/tournepierre_a_collier
cp audio/tourterelle_turque/11632.mp3 src_audio/tourterelle_turque
cp audio/tourterelle_turque/11632.mp3.properties src_audio/tourterelle_turque
cp audio/tourterelle_turque/77301.mp3 src_audio/tourterelle_turque
cp audio/tourterelle_turque/77301.mp3.properties src_audio/tourterelle_turque
cp audio/traquet_isabelle/112773.mp3 src_audio/traquet_isabelle
cp audio/traquet_isabelle/112773.mp3.properties src_audio/traquet_isabelle
cp audio/traquet_motteux/110738.mp3 src_audio/traquet_motteux
cp audio/traquet_motteux/110738.mp3.properties src_audio/traquet_motteux
cp audio/traquet_motteux/25060.mp3 src_audio/traquet_motteux
cp audio/traquet_motteux/25060.mp3.properties src_audio/traquet_motteux
cp audio/traquet_motteux/80307.mp3 src_audio/traquet_motteux
cp audio/traquet_motteux/80307.mp3.properties src_audio/traquet_motteux
cp audio/traquet_oreillard/36021.mp3 src_audio/traquet_oreillard
cp audio/traquet_oreillard/36021.mp3.properties src_audio/traquet_oreillard
cp audio/traquet_oreillard/48161.mp3 src_audio/traquet_oreillard
cp audio/traquet_oreillard/48161.mp3.properties src_audio/traquet_oreillard
cp audio/traquet_oreillard/81169.mp3 src_audio/traquet_oreillard
cp audio/traquet_oreillard/81169.mp3.properties src_audio/traquet_oreillard
cp audio/traquet_rieur/30423.mp3 src_audio/traquet_rieur
cp audio/traquet_rieur/30423.mp3.properties src_audio/traquet_rieur
cp audio/traquet_rieur/30424.mp3 src_audio/traquet_rieur
cp audio/traquet_rieur/30424.mp3.properties src_audio/traquet_rieur
cp audio/turnix_d_andalousie/45720.mp3 src_audio/turnix_d_andalousie
cp audio/turnix_d_andalousie/45720.mp3.properties src_audio/turnix_d_andalousie
cp audio/vanneau_eperonne/39426.mp3 src_audio/vanneau_eperonne
cp audio/vanneau_eperonne/39426.mp3.properties src_audio/vanneau_eperonne
cp audio/vanneau_huppe/67486.mp3 src_audio/vanneau_huppe
cp audio/vanneau_huppe/67486.mp3.properties src_audio/vanneau_huppe
cp audio/vanneau_huppe/69854.mp3 src_audio/vanneau_huppe
cp audio/vanneau_huppe/69854.mp3.properties src_audio/vanneau_huppe
cp audio/vanneau_huppe/91138.mp3 src_audio/vanneau_huppe
cp audio/vanneau_huppe/91138.mp3.properties src_audio/vanneau_huppe
cp audio/verdier_d_europe/28961.mp3 src_audio/verdier_d_europe
cp audio/verdier_d_europe/28961.mp3.properties src_audio/verdier_d_europe
